Update psammead-headings repo and home urls
BBC-archive/psammead pull request #100
Opened 2018-12-04 14:33 UTC by radiocontrolled

Resolves https://github.com/BBC-News/psammead/issues/97

Fixes repo and homepage urls in the `package.json`

- [N/A] Tests added for new features
- [ ] Test engineer approval

2018-12-04 14:38 UTC, dr3 requested changes

2018-12-04 14:38 UTC, dr3 commented on packages/components/psammead-headings/package.json
> +    "url": "https://github.com/BBC-News/psammead/tree/latest/packages/components/psammead-headings"
As this updates the content on the NPM package we should bump and publish this change

2018-12-04 16:32 UTC, dr3 submitted a review, later dismissed

2018-12-04 16:46 UTC, sareh commented on packages/components/psammead-headings/package.json
>  {
You'll need to add the `package-lock.json` changes too, to this PR. (so the version number matches that in the `package.json`)

2018-12-05 09:46 UTC, sareh approved these changes
👍 Looks great!

2018-12-05 09:49 UTC, bcmn approved these changes

2018-12-05 11:10 UTC, merged