Fix serifMedium font
BBC-archive/psammead pull request #1066
Opened 2019-07-11 08:41 UTC by EinsteinCarrey

Resolves #NUMBER

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-11 09:11 UTC, andrew-nowak requested changes
package lock needs updating

2019-07-11 09:49 UTC, andrew-nowak approved these changes

2019-07-11 09:52 UTC, ghost approved these changes

2019-07-12 14:28 UTC, sadickisaac commented
@EinsteinCarrey Resolve conflicts.

2019-07-12 14:34 UTC, david-boydell commented
Looks good, this is ready for merge.

2019-07-15 15:27 UTC, dr3 approved these changes

2019-07-15 15:27 UTC, merged