poc localising relative timestamps
BBC-archive/psammead pull request #1067
Opened 2019-07-11 08:51 UTC by aacn500

Resolves #NUMBER

**Overall change:** Replacing the existing relative timestamp logic with moment and everything... pretty much just works

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-11 09:55 UTC, sadickisaac commented
This looks great. we will need to add the locales not present in moment. just like we have done with `pcm`.

2019-07-12 15:00 UTC, aacn500 commented
More investigation found that the relative timestamps get rounded into categories, such as '45 seconds ago' => 'a minute ago'. https://momentjs.com/docs/#/displaying/fromnow/

Fortunately, it's incredibly easy to configure this behaviour in moment 🌮 https://momentjs.com/docs/#/customization/relative-time-threshold/

556b4a1 is an example of doing such configuration (only in the storybook though)

2019-07-17 13:51 UTC, aacn500 commented on packages/containers/psammead-timestamp-container/src/index.stories.jsx
> +    inputProvider([], ({ locale, script, service }) => (
ideally this would use the dirDecorator, but that doesn't pass the locale through yet

2019-07-17 18:22 UTC, dr3 requested changes
Can I be a pain soz? Can you add assertion tests with the examples in the stories please? E.g. 30, 59 seconds etc

From the PR and issues its not clear of their intended outcome, and if that changes in the future via breaking it, we might not notice

E.g locally I can see anything <1 min ago equals `a minute ago`, but the buttons with `30 seconds ago` and `59 seconds ago` doesnt imply much

2019-07-18 09:48 UTC, aacn500 commented
Added a bunch of unit tests :)

2019-07-18 13:00 UTC, dr3 approved these changes

2019-07-18 13:20 UTC, j-pendlebury approved these changes
![](https://media.giphy.com/media/31lPv5L3aIvTi/giphy.gif)

yay, wooo, noice 👏👍

2019-07-22 11:09 UTC, jblaut commented
translations need to be verified

2019-07-22 12:17 UTC, david-boydell commented
I'm looking at Yoruba and when I select a value less than two minutes the timestamp reads "_ìsẹjú kan kọjá_" .This translates to "_one week passed_". Others make no sense in google translate.

I think we should merge this so editorial can check it either on https://bbc.github.io/psammead/ or in Simorgh.

2019-07-22 14:02 UTC, staylos92 commented
@aacn500 this is now in Ready for Merge but is marked as DO NOT MERGE. What needs to happen with this now?

2019-07-22 14:37 UTC, aacn500 commented
@staylos92 I'm waiting for a decision on what to do with the unverified translations, I will place it in the blocked column so that this column isn't cluttered

2019-07-22 16:24 UTC, aacn500 commented
externally blocked waiting on confirming the yoruba translations with editorial

2019-07-26 13:35 UTC, aacn500 commented
Now unblocked, the rest of work for this PR is fulfilled by updating `@bbc/psammead-locales` to 1.1.0 and importing the Yoruba translation overrides into `packages/containers/psammead-timestamp-container/src/index.stories.jsx`. When this work is pulled into Simorgh, the same should happen there.

2019-07-26 16:12 UTC, dr3 approved these changes

2019-07-30 07:02 UTC, david-boydell commented
This is ready for merge

2019-07-30 08:30 UTC, merged