Add Horizontal Rule component
BBC-archive/psammead pull request #122
Opened 2018-12-05 18:10 UTC by sareh

Resolves #53

Creates the `@bbc/psammead-horizontal-rule` component. Originally in [Simorgh](https://github.com/BBC-News/simorgh)

- [ ] Tests added for new features
- [ ] Test engineer approval

2018-12-05 18:26 UTC, sareh commented
The unit tests pass, but since Storybook on `latest` is broken, the component can't be viewed yet.

2018-12-06 10:24 UTC, dr3 approved these changes
![](https://media.giphy.com/media/10UtqJNULHPfxe/giphy.gif)

2018-12-06 13:43 UTC, ChrisBAshton requested changes
Changelog.md and Readme tweaks please 👍 otherwise looks great!

2018-12-06 13:43 UTC, ChrisBAshton commented on packages/components/psammead-horizontal-rule/CHANGELOG.md
> +| 0.1.0   | [PR#](https://github.com/BBC-News/psammead/pull/) Create initial package with Horizontal Rule component pulled in from [Simorgh](https://github.com/BBC-News/simorgh). |
```suggestion
| 0.1.0   | [PR#122](https://github.com/BBC-News/psammead/pull/122) Create initial package with Horizontal Rule component pulled in from [Simorgh](https://github.com/BBC-News/simorgh). |
```

2018-12-06 13:43 UTC, ChrisBAshton commented on packages/components/psammead-horizontal-rule/README.md
> +    <HorizontalRule/>
```suggestion
  <HorizontalRule />
```

(nesting seems off)

2018-12-06 13:43 UTC, ChrisBAshton commented on packages/components/psammead-horizontal-rule/README.md
> +    <HorizontalRule/>
```suggestion
  <HorizontalRule />
```

(nesting seems off)

2018-12-10 12:03 UTC, sareh commented
Closed as we're not using Horizontal Rule anymore.

2018-12-10 12:03 UTC, closed without merging