stricter grid support detection
BBC-archive/psammead pull request #1234
Opened 2019-07-16 09:14 UTC by aacn500

Part one of #751

**Overall change:** Adds a CSS feature detection query that will hopefully avoid the issues in bbc/simorgh#2063

**Code changes:**

- Export a feature detection query from `@bbc/psammead-styles/detection`
- Add a story showing the difference between `@supports (display: grid)` and `@supports (${detection.gridDetection})`

**Question to reviewers**
- Which of the following two do you prefer?

```js
const someGridUsingComponent = css`
  @supports (${gridDetection}) {
    display: grid;
    /* grid CSS */
  }
  /* fallback CSS */
`;
```

```js
const someGridUsingComponent = css`
  ${supportsGrid} {
    display: grid;
    /* grid CSS */
  }
  /* fallback CSS */
`;
```

**Note to tester**
This PR doesn't change any psammead components nor any of Simorgh so there's not much to test... This might be the time to test which browsers respond to which supports queries?

I've made a tiny example page which does essentially the same thing as the story I added in this PR (with a few additions) -- www.nowak.me.uk/rb -- the important markers are the top two `supports-grid` and `supports-fit-content`. Hopefully most/all browsers except for the KaiOS browser are either both green or both red on those values. Would be happy & interested in pairing on testing this and seeing which browsers do what if that's of any help

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-16 14:33 UTC, sadickisaac commented on packages/utilities/psammead-styles/README.md
> +  @supports (${gridDetection}) {
```suggestion
  @supports (${grid}) {
```
reads a little bit nicer IMO.

2019-07-16 14:39 UTC, ghost requested changes
Update `package.json`, `package-lock.json` and `CHANGELOG.md`

2019-07-16 15:30 UTC, ghost requested changes

2019-07-16 15:30 UTC, sadickisaac commented on packages/utilities/psammead-styles/CHANGELOG.md
> +| 1.2.0 | [PR#?](https://github.com/bbc/psammead/pull/?) Add custom CSS Grid feature detector |
```suggestion
| 1.2.0 | [PR#1234](https://github.com/bbc/psammead/pull/1234) Add custom CSS Grid feature detector |
```

2019-07-16 19:47 UTC, dr3 approved these changes

2019-07-17 04:43 UTC, ghost approved these changes

2019-07-18 11:06 UTC, david-boydell commented
Cool, thanks for the test page @aacn500, much appreciated. This is ready for merge.

2019-07-18 11:49 UTC, merged