1204 drop off screen text
BBC-archive/psammead pull request #1240
Opened 2019-07-16 12:18 UTC by Bopchy

Resolves #1204 

**Overall change:** _Remove unused media indicator offscreen text._

**Code changes:**

- _Remove unused offscreen text from the MediaIndicator component._
- _Update tests._
- _Update stories._
- _Update snapshots._
---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-16 13:15 UTC, Bopchy commented
Created https://github.com/bbc/psammead/issues/1242 to update StoryPromo to use this version of MediaIndicator

2019-07-16 14:03 UTC, andrew-nowak approved these changes
deleting dead code :yay:

2019-07-16 14:18 UTC, ghost requested changes
Update `version` on `package-lock.json`.

2019-07-17 07:49 UTC, ghost requested changes
Now that we don't use the offscreen text in `media-indicator`, we should remove `psammead-visually-hidden-text` from `media-indicator` dependancies.

2019-07-17 12:47 UTC, ghost approved these changes

2019-07-17 14:17 UTC, andrew-nowak requested changes
looking again at this, the API is being changed so this is technically a breaking change and should be a major version bump

2019-07-17 14:17 UTC, aacn500 commented on packages/components/psammead-media-indicator/CHANGELOG.md
> +| 2.1.1 | [PR#1240](https://github.com/bbc/psammead/pull/1240) Remove unused offscreen text |
```suggestion
| 3.0.0 | [PR#1240](https://github.com/bbc/psammead/pull/1240) Remove unused offscreen text |
```

2019-07-17 14:17 UTC, aacn500 commented on packages/components/psammead-media-indicator/package.json
> +  "version": "2.1.1",
```suggestion
  "version": "3.0.0",
```

2019-07-17 14:17 UTC, aacn500 commented on packages/components/psammead-media-indicator/package-lock.json
> +  "version": "2.1.1",
```suggestion
  "version": "3.0.0",
```

2019-07-17 17:48 UTC, dr3 commented on lerna-debug.log
> +0 silly argv { _: [ 'exec' ],
😱

2019-07-17 17:55 UTC, dr3 reviewed
I think this should have been a minor change, as while the API has changed, its not breaking. Also theres a lerna debug file? TIL theyre a thing 🙈 Other than that, LGTM

2019-07-18 08:48 UTC, j-pendlebury approved these changes
Looks good to me 👍⭐️

2019-07-18 09:49 UTC, andrew-nowak approved these changes

2019-07-22 13:05 UTC, david-boydell commented
Cool, this is ready for merge.

2019-07-22 13:51 UTC, merged