Use the npm client instead of exec in the version check script
BBC-archive/psammead pull request #1357
Opened 2019-07-17 10:22 UTC by DemonusPC

Resolves #1081

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-17 18:56 UTC, dr3 requested changes
Personally I dont think security matters here, hence why I didnt do this stuff when i wrote this code. We dont run forks, and this code only runs on merge, after code reviews. If someone was going to abuse this script, they could just change the entire script to run what they want, it would equally have to get past 2 devs (one being a code owner) to run.

If someone malicious was to get a branch to run on jenkins, they would be much better off using `child_process` `exec` in a test file somewhere and running what ever they wanted. That wouldn't even need to be merged to run.

Anyway 🙈 If we do care about security for this script, Adding this to any package.json will create a file called `hey.txt`, or do anything it wants, so we should probably limit it too
```
"publishConfig": {
 "access": "restricted; echo 'hello' > hey.txt; "
},
```

2019-07-18 09:11 UTC, benjaminhobbs commented
> Personally I dont think security matters here, hence why I didnt do this stuff when i wrote this code. We dont run forks, and this code only runs on merge, after code reviews. If someone was going to abuse this script, they could just change the entire script to run what they want, it would equally have to get past 2 devs (one being a code owner) to run.
> 
> If someone malicious was to get a branch to run on jenkins, they would be much better off using `child_process` `exec` in a test file somewhere and running what ever they wanted. That wouldn't even need to be merged to run.
> 
> Anyway 🙈 If we do care about security for this script, Adding this to any package.json will create a file called `hey.txt`, or do anything it wants, so we should probably limit it too
> 
> ```
> "publishConfig": {
>  "access": "restricted; echo 'hello' > hey.txt; "
> },
> ```

My only response is to clarify that we will run forks in the future.

2019-07-18 09:15 UTC, dr3 commented
>My only response is to clarify that we will run forks in the future.

@benjaminhobbs How will we stop someone from editing our publish script to do what they want? You can lock down a jenkins pipeline so if you change `withCredentials` the jenkins file wont run, to avoid easily accessing the credentials, but you cant stop it running if someone changes the publish scripts AFAIK.

2019-07-18 09:18 UTC, benjaminhobbs commented
> > My only response is to clarify that we will run forks in the future.
> 
> @benjaminhobbs How will we stop someone from editing our publish script to do what they want? You can lock down a jenkins pipeline so if you change `withCredentials` the jenkins file wont run, to avoid easily accessing the credentials, but you cant stop it running if someone changes the publish scripts AFAIK.

I'm not going to answer security questions on a public repo, will reply IRL.

2019-07-18 10:37 UTC, DemonusPC commented
> I dont think security matters here
Security should matter no matter what you are writing. The code should be secure by default, even if it is a dumb script that checks for packages. This is because someone smarter than all of us could come along still find a way to exploit it. 
On top of this, this refactoring improves the speed of this script significantly. The update is near instant.

2019-07-22 09:50 UTC, dr3 requested changes
>Security should matter no matter what you are writing. The code should be secure by default, even if it is a dumb script that checks for packages.

Adding this to any package.json will create a file called `hey.txt`, or do anything it wants, so we should limit it too
```
"publishConfig": {
 "access": "restricted; echo 'hello' > hey.txt; "
},
```

2019-07-30 09:44 UTC, DemonusPC commented
Ok I don't care about this anymore. Ignore the security and performance improvements.

2019-07-30 09:44 UTC, closed without merging