Add input provider for Consent banner story
BBC-archive/psammead pull request #1366
Opened 2019-07-18 15:30 UTC by sareh

Resolves #700

**Overall change:** Updates consent banner's storybook to have placeholder text. Can use the drop-down to select a different script. 

**Code changes:**

- Updates consent banner's storybook to have placeholder text. 
<img width="1430" alt="Screen Shot 2019-07-18 at 16 27 58" src="https://user-images.githubusercontent.com/3028997/61470458-0c0fa680-a979-11e9-8f07-ad6ee5d42c68.png">

When selecting from the drop-down, you should see 
---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-19 07:45 UTC, sareh commented
Talking with Clare and Laura, they were happy with just having placeholder text rather than having the exact translation used in Storybook, so that's what I've implemented here.

2019-07-19 09:16 UTC, ryanmccombe commented on packages/components/psammead-consent-banner/src/index.stories.jsx
> +        { name: 'acceptText', defaultText: 'OK' },
Doesn't look like the `acceptText` or `rejectText` knobs are being used for anything - the `text` knob is being used 3 times instead

2019-07-19 09:16 UTC, ryanmccombe approved these changes

2019-07-22 08:29 UTC, dr3 requested changes
https://github.com/bbc/psammead/pull/1366/files#r305270960

2019-07-22 09:40 UTC, dr3 approved these changes

2019-07-22 09:40 UTC, sareh commented
Thanks, I've just made the changes. :)

2019-07-23 09:16 UTC, paruchurisilpa commented
Done regression on storybook and looks good to me, can be merged..

2019-07-23 10:29 UTC, dr3 approved these changes

2019-07-23 10:30 UTC, merged