Use new custom grid detector
BBC-archive/psammead pull request #1408
Opened 2019-07-22 14:25 UTC by DenisBBC

Resolves #1364

**Overall change:** 
Use new custom `grid` detector from `@bbc/psammead-styles/detection` in `psammead-sitewide-links` and `psammead-story-promo`.

**Code changes:**
- Import and use the `grid` detector in the `StoryPromo` and `List`
- Update snaps

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-22 15:02 UTC, dr3 approved these changes
![](https://media.giphy.com/media/kBZBlLVlfECvOQAVno/giphy.gif)

2019-07-22 15:30 UTC, andrew-nowak requested changes
This doesn't seem to be enough for sitewide links 😞 
![image](https://user-images.githubusercontent.com/10963046/61645031-b8b19700-ac9d-11e9-9f11-878e9d07e577.png)
(Firefox 48 with `layout.css.grid.enabled` toggled on)

It looks like the styled `ul` has a `displays: grid` declaration outside of a `@supports` block, I think one is needed

2019-07-23 14:26 UTC, ghost approved these changes

2019-07-23 14:52 UTC, andrew-nowak approved these changes

2019-07-26 08:30 UTC, david-boydell commented
This is great, ready for merge.

2019-07-26 08:33 UTC, merged