Change copyright text prop-type
BBC-archive/psammead pull request #1524
Opened 2019-07-30 12:23 UTC by EinsteinCarrey

Resolves #NUMBER

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-30 13:31 UTC, ghost submitted a review, later dismissed

2019-07-30 13:31 UTC, sadickisaac commented on packages/components/psammead-sitewide-links/README.md
> +| copyrightText | Node                | Yes      | N/A     | `<span>Copyright BBC News</span>`                            |
include the `copyright` symbol in the example

2019-07-31 08:48 UTC, DenisHdz requested changes

2019-07-31 08:48 UTC, DenisBBC commented on packages/components/psammead-sitewide-links/CHANGELOG.md
> +| 3.0.0 | [PR#1524](https://github.com/bbc/psammead/pull/1524) Change `copyrighText` prop from `sting` to `node`  |
```suggestion
| 3.0.0 | [PR#1524](https://github.com/bbc/psammead/pull/1524) Change `copyrighText` prop from `string` to `node`  |
```

2019-07-31 09:31 UTC, j-pendlebury reviewed
Just one thing 🙈

2019-07-31 09:31 UTC, jblaut commented on packages/components/psammead-sitewide-links/README.md
> +  copyrightText: <span>@ BBC News<span>,
```suggestion
  copyrightText: <span>@ BBC News</span>,
```

2019-07-31 10:15 UTC, DenisHdz approved these changes
LGTM

2019-07-31 10:57 UTC, Bopchy approved these changes

2019-07-31 12:51 UTC, j-pendlebury approved these changes

2019-07-31 12:56 UTC, staylos92 commented
This doesn't need testing by a tester

2019-07-31 13:17 UTC, merged