Update PR welcome links in readme
BBC-archive/psammead pull request #173
Opened 2018-12-10 10:14 UTC by dr3

Resolves #170

Updates PR's welcome link

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2018-12-10 16:38 UTC, sareh requested changes
This all looks great. Unfortunately, since you created this, psammead-paragraph & psammead-visually-hidden-text have been updated, so you'll need to bump the relevant package.json, package-lock.json & changelog files.

2018-12-11 10:07 UTC, ChrisBAshton approved these changes

2018-12-11 12:25 UTC, bcmn commented
Bear in mind this will sit oddly with #129. I don’t think there'll be any prompt to fix either branch.

2018-12-11 12:32 UTC, sareh approved these changes
Looks good!

2018-12-11 14:50 UTC, merged