Add contact details to README
BBC-archive/psammead pull request #177
Opened 2018-12-10 12:02 UTC by radiocontrolled

Resolves https://github.com/BBC-News/psammead/issues/135

Adds Psammead contact details to readme.

- [X] I have assigned myself to this PR and the corresponding issues
- [N/A] Tests added for new features
- [ ] Test engineer approval

2018-12-10 12:05 UTC, dr3 commented on README.md
> +Contact us by email on [PsammeadMaintainers@bbc.co.uk](mailto:PsammeadMaintainers@bbc.co.uk), or find us on Slack at #psammead.
```suggestion
Contact us by email on [PsammeadMaintainers@bbc.co.uk](mailto:PsammeadMaintainers@bbc.co.uk), or find us on Slack at #psammead in the bbcnews workspace. 
```

2018-12-11 10:00 UTC, dr3 requested changes
Just that one change

2018-12-11 10:52 UTC, dr3 approved these changes

2018-12-11 11:26 UTC, ChrisBAshton approved these changes

2018-12-11 11:26 UTC, merged

2018-12-11 11:26 UTC, ChrisBAshton commented
Merged as James was happy for us to merge it without Test step.