Make psammead-styles treeshakable
BBC-archive/psammead pull request #1777
Opened 2019-08-15 14:00 UTC by FK78

Resolves #1688 

**Overall change:** _Restructures package to use nested `package.json`s to expose ESM code._

**Code changes:**

- _Restructures package to use nested `package.json`s to expose ESM code._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-08-15 14:04 UTC, thekp requested changes
fix linting

2019-08-15 14:26 UTC, thekp approved these changes

2019-08-16 08:56 UTC, aacn500 commented on packages/utilities/psammead-styles/colours/package.json
> +  "private": "true",
```suggestion
  "private": true,
```

2019-08-16 08:56 UTC, aacn500 commented on packages/utilities/psammead-styles/detection/package.json
> +  "private": "true",
```suggestion
  "private": true,
```

2019-08-16 08:57 UTC, aacn500 commented on packages/utilities/psammead-styles/font-styles/package.json
> +  "private": "true",
```suggestion
  "private": true,
```

2019-08-16 08:57 UTC, aacn500 commented on packages/utilities/psammead-styles/fonts/package.json
> +  "private": "true",
```suggestion
  "private": true,
```

2019-08-16 09:03 UTC, dr3 reviewed
LGTM after @aacn500's suggestion :)

2019-08-17 19:58 UTC, dr3 approved these changes

2019-08-17 20:54 UTC, benjaminhobbs commented
@dependabot rebase

2019-08-19 08:53 UTC, merged