Document component approach
BBC-archive/psammead pull request #181
Opened 2018-12-11 09:59 UTC by bcmn

Resolves #137 

The readme seems really approachable post-#174, so I was keen to keep it clean when approaching this ticket. As such, I figured we could link of to more in-depth explanations of the four intended sub-sections of Psammead (components, contexts, themes & utilities).

Based this on the notes coming out of the collaboration day the other week. In those, there's a lot of talk of examples or simple "dos & don'ts", but found those looked a little too much of an info-dump when I attempted to add some.

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2018-12-11 12:27 UTC, ChrisBAshton requested changes
Good start! Just fix the markdown 👍

2018-12-11 12:27 UTC, ChrisBAshton commented on README.md
> + * Utilities - Commonly shared Psammead dependencies, and fundamentals to aid building additional GEL-compliant components.
```suggestion
 * [Utilities](./packages/utilities) - Commonly shared Psammead dependencies, and fundamentals to aid building additional GEL-compliant components.
```

2018-12-11 12:27 UTC, ChrisBAshton commented on packages/components/README.md
> + In summary, Psammead components should be almost exclusively concerned with how the component appears, and should avoid fetching or mutating data. Instead, these data fetching and mutating operation
Perhaps link to Simorgh as an example here.

2018-12-11 12:27 UTC, ChrisBAshton commented on packages/components/README.md
> + ## What is a Psammead component?
Dodgy markup in this file - everything after line 1 has a ` ` space before it 🤔

2018-12-11 12:27 UTC, ChrisBAshton commented on packages/components/README.md
> + These principles help Psammead components be reused across fundamentally different projects and back-ends.
```suggestion
These principles help Psammead components to be reusable across different projects and back-ends.
```

2018-12-12 10:57 UTC, ChrisBAshton approved these changes
Approved. *signs*

![](https://media.giphy.com/media/xTiTntToR0nSNgwAU0/giphy.gif)

2018-12-12 14:55 UTC, sareh approved these changes
:+1: Looks great!

2018-12-12 15:43 UTC, merged