Bump root dependencies during Talos execution
BBC-archive/psammead pull request #1828
Opened 2019-08-19 15:00 UTC by pharingee

Resolves #1753 

**Overall change:** 
Change upgrade dependencies command to upgrade root dependencies as well

**Code changes:**
- Changed /scripts/upgradeDependencies/index.js

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-08-22 11:06 UTC, dr3 requested changes
Just one thing which I noticed :P Otherwise LGTM

2019-08-22 11:06 UTC, dr3 commented on scripts/publish/test/getPackages.test.js
> +  it('returns array of packages with the root package and two other packages found', () => {
Just realised.. this test isnt testing the correct file... `scripts/publish/test/getPackages.test.js` doesnt test `scripts/publish/src/getPackages.js` and infact nothing uses it :L 

Can you delete `scripts/publish/src/getPackages.js` please, and combine `scripts/publish/test/getPackages.test.js` and `scripts/utilities/getPackages/index.test.js` please

2019-08-22 11:09 UTC, pharingee commented on scripts/publish/test/getPackages.test.js
> +  it('returns array of packages with the root package and two other packages found', () => {
Ok.

2019-08-22 12:59 UTC, dr3 approved these changes
![](https://media.giphy.com/media/U2O50cAkpmTjG/giphy.gif)

2019-08-23 12:01 UTC, dr3 commented
@pharingee this has 78% test coverage according to codeclimate, any ideas where its lacking?

2019-08-23 12:12 UTC, pharingee commented
Not really. I think testing `parseUpgradedPackages` for the base package might be the only test missing here. I'll add that to it.

2019-08-23 12:18 UTC, chris-hinds approved these changes

2019-08-23 12:35 UTC, merged