Talos - Improve PR title
BBC-archive/psammead pull request #1843
Opened 2019-08-21 15:46 UTC by FK78

Resolves #1754

**Overall change:** _Shortened the PR titles_

**Code changes:**

- _Created new function called getPackageNames._
- _Created new file with unit tests for new function._
- _Added unit test to createPullRequest for new function._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-08-21 15:51 UTC, dr3 requested changes
LGTM, just 2 small things :)

2019-08-21 15:51 UTC, dr3 commented on scripts/talos/createPullRequest/getPackageNames/index.test.js
> +  it('should shorten the title', () => {
```suggestion
  it('should shorten the title when more than 3 packages are provided', () => {
```

2019-08-21 15:51 UTC, dr3 commented on scripts/talos/createPullRequest/getPackageNames/index.test.js
> +  it('should not shorten the title', () => {
```suggestion
  it('should not shorten the title when less than 3 packages are provided', () => {
```

2019-08-21 17:16 UTC, dr3 approved these changes
![](https://media.giphy.com/media/sLs8Ll8Qx51xm/giphy.gif)

2019-08-22 07:48 UTC, chris-hinds approved these changes

2019-08-22 09:48 UTC, thekp approved these changes
![](https://media.giphy.com/media/9xuUhwozi3qvJdPogI/giphy.gif)

2019-08-22 10:47 UTC, merged