README.md update
BBC-archive/psammead pull request #1849
Opened 2019-08-22 13:07 UTC by FK78

Resolves #1846 

**Overall change:** _Update README.md_

**Code changes:**

- _Added desc for exported functions._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-08-22 13:10 UTC, thekp approved these changes

2019-08-22 13:32 UTC, oluoluoxenfree approved these changes

2019-08-22 13:33 UTC, thekp approved these changes

2019-08-22 13:34 UTC, thekp approved these changes

2019-08-22 13:35 UTC, thekp approved these changes

2019-08-22 13:46 UTC, thekp approved these changes
🎉

2019-08-23 08:47 UTC, dr3 commented on package.json
> +    "react": "^16.9.0",
We need to change these all at once, with the packages. Can you undo these please?

2019-08-23 08:48 UTC, dr3 requested changes

2019-08-23 08:48 UTC, dr3 commented on package.json
> +    "@bbc/psammead-test-helpers": "^1.3.0",
This will need a changelog change and base level package bump :)

2019-08-23 09:06 UTC, dr3 commented on CHANGELOG.md
> +| 1.5.3 | [PR#1849](https://github.com/bbc/psammead/pull/1849) Update README.md |
```suggestion
| 1.5.3 | [PR#1849](https://github.com/bbc/psammead/pull/1849) Bump @bbc/psammead-test-helpers `^1.1.1` to `^1.3.1`  |
```

2019-08-23 09:45 UTC, thekp commented
@dr3 we had to bump the base package to `1.3.0` because `1.3.1` has not been published yet.

2019-08-23 09:54 UTC, dr3 commented on CHANGELOG.md
> +| 1.5.3 | [PR#1849](https://github.com/bbc/psammead/pull/1849) Bump @bbc/psammead-test-helpers `^1.1.1` to `^1.3.1`  |
```suggestion
| 1.5.3 | [PR#1849](https://github.com/bbc/psammead/pull/1849) Bump @bbc/psammead-test-helpers `^1.1.1` to `^1.3.0`  |
```

2019-08-23 09:55 UTC, dr3 commented on packages/utilities/psammead-test-helpers/README.md
> +| setWindowValue             | key, value                                  | {Allows you to set variables on the window (eg. location) that are normally not writable}
```suggestion
| setWindowValue             | key, value                                  | Allows you to set variables on the window (eg. location) that are normally not writable                                                                                                                                        |
```

2019-08-23 09:55 UTC, dr3 commented on packages/utilities/psammead-test-helpers/README.md
> +| resetWindowValue           | key, value                                  | {Allows you to reset the WindowValues that are previously overwritten by the setWindowValue function}
```suggestion
| resetWindowValue           | key, value                                  | Allows you to reset the WindowValues that are previously overwritten by the setWindowValue function                                                                                                                           |
```

2019-08-23 09:57 UTC, dr3 approved these changes

2019-08-23 10:04 UTC, thekp approved these changes

2019-08-23 10:08 UTC, merged