Updated npm scripts
BBC-archive/psammead pull request #1940
Opened 2019-08-29 14:13 UTC by lokh01

Resolves #1939

**Overall change:**
Reduced overall number of scripts from 29 to 20 through removing redundant scripts and merging scripts together.

**Code changes:**
Replaced/Merged into to other scripts
- ```test:lint:css``` merged into ```test:lint```
- ```forced-package-lock-https``` made into script in /scripts

Removals
- ```postinstall``` 
Use ```npm run build``` instead.
- ```updateSnapshots```  
Use ```npm run test:unit -- -u``` instead.
- ```test:unit:watch``` 
Use ```npm run test:unit --watch``` instead.
- ```test:packages``` 
Use ```npx lerna run test``` instead.
- ```install:packages:link```
Use ```npm run install:packages --force-local``` instead.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-02 08:50 UTC, dr3 requested changes
LGTM just one tweak, can you make sure all readmes are updated too, if needed :)

2019-09-02 08:50 UTC, dr3 commented on package.json
>      "talos": "node scripts/talos/cli",
We can remove talos from here, and just call it from the make file, it shouldnt really we called locally :P

2019-09-03 08:36 UTC, dr3 commented on package.json
> +    "bumpPackages": "node scripts/bumpPackages/cli",
This is now in here twice? line 12 is a duplicate thats out of alphabetical order

2019-09-03 08:36 UTC, dr3 commented on package.json
>      "bumpPackages": "node scripts/bumpPackages/cli",
```suggestion
```

2019-09-03 08:36 UTC, dr3 approved these changes
Great work :)

2019-09-03 09:30 UTC, HarveyPeachey approved these changes
LGTM, do you need to update the changelog.md with these changes?

2019-09-03 11:07 UTC, chris-hinds approved these changes

2019-09-04 07:50 UTC, merged