Talos - Bump react, styled-components, react-dom...
BBC-archive/psammead pull request #1942
Opened 2019-08-29 22:06 UTC by bbc-news-frameworks

👋 The following packages have been published:
react
styled-components
react-dom
react-test-renderer

So we need to bump them in the following packages:
psammead
@bbc/psammead-amp-geo
@bbc/psammead-image
@bbc/psammead-image-placeholder
@bbc/psammead-navigation
@bbc/psammead-media-indicator
@bbc/psammead-consent-banner
@bbc/psammead-story-promo-list
@bbc/psammead-assets
@bbc/psammead-sitewide-links
@bbc/psammead-media-player
@bbc/psammead-section-label
@bbc/psammead-story-promo
@bbc/psammead-brand
@bbc/psammead-timestamp-container

2019-08-29 22:10 UTC, dr3 approved these changes

2019-08-30 14:40 UTC, ghost requested changes
Resolve conflicts

2019-09-02 03:37 UTC, ghost approved these changes

2019-09-02 03:42 UTC, ghost submitted a review, later dismissed
Just noticed the `alpha-version` bump.

2019-09-02 03:42 UTC, sadickisaac commented on packages/components/psammead-media-player/package.json
> +  "version": "1.0.1",
Bumping an alpha version to stable.
```suggestion
  "version": "1.0.1-alpha.2",
```
I have a PR to fix the alpha versioning https://github.com/bbc/psammead/pull/1949

2019-09-02 07:35 UTC, jroebu14 approved these changes

2019-09-02 09:00 UTC, staylos92 commented
LGTM 👍

2019-09-02 09:01 UTC, merged