force package-lock.json to reference https
BBC-archive/psammead pull request #195
Opened 2018-12-13 09:47 UTC by ChrisBAshton

This is currently the advised thing to do while NPM fixes the bug: https://npm.community/t/npm-install-downgrading-resolved-packages-from-https-to-http-registry-in-package-lock-json/1818/3

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2018-12-13 09:50 UTC, bcmn submitted a review, later dismissed

2018-12-13 10:07 UTC, sareh submitted a review, later dismissed
👍 Looks good

2018-12-13 14:24 UTC, sareh submitted a review, later dismissed

2018-12-13 14:34 UTC, pjlee11 commented
[Jenkins failure](https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/psammead/detail/force-https-package-lock/4/pipeline) - when running `make install` on CI the following error is thrown:

```
> @bbc/psammead@0.1.0 force-package-lock-https /var/lib/jenkins/workspace/ad_force-https-package-lock-XOD5QFKGO7J6HJG5KVAKMLMPJNORCJAULJKDNZQLHT4D6EPR5WYQ@4

> find . -type f -name "package-lock.json" -print0 | xargs -0 sed -i '' -e 's/http:\/\//https:\/\//g'

sed: can't read : No such file or directory
```

My guess is that the difference between `npm install` locally and `npm ci` on Jenkins is causing a valid error

2018-12-13 17:30 UTC, pjlee11 approved these changes

2018-12-13 17:32 UTC, pjlee11 requested changes
Jenkins failing again, now on `sh: 1: [[: not found` following the addition of `if ! [[ -n $JENKINS_HOME ]]; then \n npm run force-package-lock-https \n fi`

2018-12-14 09:06 UTC, bcmn submitted a review, later dismissed
Looks good & works locally. 👍  I also didn't know what `test -z` did until just now -- handy. 👀

2018-12-14 10:26 UTC, pjlee11 submitted a review, later dismissed
Nice solution!

![](https://media.giphy.com/media/OE6FE4GZF78nm/giphy.gif)

2018-12-14 11:12 UTC, bcmn commented
![screenshot 2018-12-14 at 11 12 09](https://user-images.githubusercontent.com/11646957/50000316-1e63d500-ff91-11e8-9d49-7a1214b0b44e.png)

The logging shows that this is altering node_modules? I can't imagine this'll ever be an issue, but it feels weird.

2018-12-14 11:13 UTC, ChrisBAshton commented
argh you're right. Needs a tighter fix...

2018-12-14 12:10 UTC, ChrisBAshton commented
Fixed!

2018-12-14 12:29 UTC, bcmn submitted a review, later dismissed

2018-12-14 12:33 UTC, dr3 requested changes

2018-12-14 12:33 UTC, dr3 commented on package.json
> +    "postshrinkwrap": "if test -z $JENKINS_HOME; then \n npm run force-package-lock-https \n fi",
```suggestion
    "postshrinkwrap": "if test -z $CI; then \n npm run force-package-lock-https \n fi",
```
Uses https://github.com/BBC-News/psammead/blob/latest/Jenkinsfile#L22

2018-12-14 12:46 UTC, sareh approved these changes
👍

2018-12-14 12:48 UTC, bcmn approved these changes

2018-12-17 10:18 UTC, jamesbrumpton commented
LGTM

2018-12-17 10:20 UTC, dr3 approved these changes

2018-12-17 10:20 UTC, merged