Add Persian and Pashto locales to Storybook
BBC-archive/psammead pull request #2000
Opened 2019-09-04 14:42 UTC by jamesdonoh

Resolves [NO ISSUE]

**Overall change:** _Adds the Persian and Pashto locales to the Utilities > Psammead Locales section on Storybook_

This was missed off https://github.com/bbc/psammead/pull/1844 - H/T @RayNjeri for spotting.

**Code changes:**

- As above

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-04 16:33 UTC, rhenshaw56 approved these changes
Ran on storybook, looks good!

2019-09-05 09:01 UTC, RayNjeri requested changes
Changelog needs to be updated to 2.1.3

2019-09-05 12:33 UTC, RayNjeri approved these changes

2019-09-05 12:56 UTC, EinsteinNjoroge approved these changes
LGTM

2019-09-05 15:36 UTC, ryanmccombe approved these changes

2019-09-06 08:20 UTC, dr3 approved these changes

2019-09-06 08:21 UTC, merged