Add global styles to `psammead-styles`
BBC-archive/psammead pull request #2021
Opened 2019-09-06 09:03 UTC by EinsteinCarrey

Resolves #NUMBER

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-06 09:50 UTC, EinsteinCarrey commented
I'm not sure about this implementation, kindly confirm I'm on the right track

2019-09-06 09:55 UTC, dr3 reviewed
Hey :) I see the issue says "Our font-faces should not be included initially, since they will vary depending on the service" but I would expect `${({ fonts }) => fonts && createFontStyles(fonts)}` to stay in here, so we can pass the fonts in in simorgh?

They will vary on service, but we can call it like `<GlobalStyles fonts={arrayOfServiceFonts} />` :)

Otherwise, this PR looks great :)

2019-09-11 10:10 UTC, dr3 requested changes
Looks great, just a couple things :)

2019-09-11 10:10 UTC, dr3 commented on packages/utilities/psammead-styles/CHANGELOG.md
> +| 2.1.5 | [PR#2021](https://github.com/bbc/psammead/pull/2021) Export global styles |
This should be a `minor` change as it adds functionality :)

2019-09-11 10:10 UTC, dr3 commented on packages/utilities/psammead-styles/src/__snapshots__/global-styles.test.jsx.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
This file doesn't contain `Sans-Serif` which is passed in `it('should handle global-styles with fonts props', () => {`?

2019-09-11 10:33 UTC, sareh requested changes
Looks good so far! I've suggested some changes here.

2019-09-11 10:33 UTC, sareh commented on packages/utilities/psammead-styles/CHANGELOG.md
> +| 2.1.5 | [PR#2021](https://github.com/bbc/psammead/pull/2021) Export global styles |
Can you please update the package Readme with a description of how to use the `global-styles` import. A usage example would be great. One including fonts so that people can use them.

2019-09-11 10:33 UTC, sareh commented on packages/utilities/psammead-styles/src/global-styles.js
> +    ${({ fonts }) => fonts && createFontStyles(fonts)}
This creation of fonts in the `createFontStyles` method is very specific to our Simorgh application. It'd be better to decouple our implementation in Simorgh from this package, but retaining the ability to pass in fonts. 
```suggestion
    ${({ fonts }) => fonts ? fonts : null;}
```

2019-09-12 11:57 UTC, sareh requested changes
Thanks for the changes. Suggested an update to the example.

2019-09-12 11:57 UTC, sareh commented on packages/utilities/psammead-styles/README.md
> +<GlobalStyles fonts={['font-family: "Sans-Serif"']}/>
Thanks for the update. 

It'd be helpful to have example usage that uses our Psammead Styles fonts like this:

```
import GlobalStyles from '@bbc/psammead-styles/global-styles';
import {
  F_REITH_SANS_REGULAR,
  F_REITH_SERIF_MEDIUM,
} from '@bbc/psammead-styles/fonts';

<GlobalStyles fonts={[
      F_REITH_SANS_REGULAR,
      F_REITH_SERIF_MEDIUM,
    ]}
/>
```

Same for usage in the unit test & reference to the readme. 

A note for others code reviewing this PR: A Storybook example would be difficult to isolate, so shouldn't be necessary for this work. After this package is updated we'll use it in the global Psammead Storybook setup. So it'll be in use throughout the Storybook application.

2019-09-12 12:06 UTC, dr3 commented on packages/utilities/psammead-styles/src/global-styles.test.jsx
> +    render(<GlobalStyles fonts={['font-family: "Sans-Serif"']} />);
I think this meant to add font faces, not font families. Just a test but good to be clear :)

2019-09-12 14:19 UTC, sareh approved these changes
👍 Looks great.

2019-09-12 14:36 UTC, sareh commented
@EinsteinCarrey After merging this in, we have two follow-up issues to use this package:  https://github.com/bbc/psammead/issues/2112 https://github.com/bbc/simorgh/issues/3718

2019-09-12 14:37 UTC, dr3 approved these changes
LGTM, great work :)

2019-09-12 16:05 UTC, merged