feat: cover base level packages #1967
BBC-archive/psammead pull request #2095
Opened 2019-09-10 12:51 UTC by mykeels

Resolves #NUMBER

**Overall change:** Expand changeScanner to cover base level packages. resolves #1967 

**Code changes:**

- _Use `git diff --name-only origin/latest` alone instead of with `/packages/*/*/*` suffix._
- _Update tests to adjust for the change._
- _Update psammead version to `1.7.12`._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-10 13:25 UTC, dr3 requested changes
LGTM, slight bug however, editing `psammead/packages/components/README.md` says
```
Branch must update CHANGELOG.md in README.md
Branch must update package-lock.json in README.md
Branch must update package.json in README.md
```
When it should be covered by `psammead`

2019-09-12 09:56 UTC, dr3 approved these changes
LGTM, great work

2019-09-12 09:58 UTC, dr3 requested changes

2019-09-12 09:58 UTC, dr3 commented on CHANGELOG.md
> +| 1.7.13 | [PR#2090](https://github.com/bbc/psammead/pull/2090) Talos - Bump Dependencies - @bbc/psammead-locales |
Not sure whats happend to this change log, looks like your going from `1.7.11` -> `1.7.13`?

2019-09-12 09:58 UTC, dr3 commented on package.json
> +  "version": "1.7.13",
```suggestion
  "version": "1.7.12",
```

2019-09-12 10:17 UTC, dr3 approved these changes

2019-09-12 16:05 UTC, thekp commented on scripts/changeScanner/getChanges.test.js
> +        'packages/components/README.md',
is `'packages/components/README.md'` , not the same as `'psammead/packages/components/README.md',` 

??

2019-09-16 06:19 UTC, mykeels commented on scripts/changeScanner/getChanges.test.js
> +        'packages/components/README.md',
Fixed!

2019-09-16 08:41 UTC, thekp commented on scripts/changeScanner/getChanges.test.js
> +        'packages/components/README.md',
thanks

2019-09-16 08:42 UTC, thekp approved these changes
👍 nice work 💯

2019-09-19 10:25 UTC, merged