add function to detect and render helmet for use in snapshots
BBC-archive/psammead pull request #2104
Opened 2019-09-12 11:04 UTC by jroebu14

**Overall change:** Adds functionality to `shouldMatchSnapshot` to include html and head tags if `react-helmet` was used inside of component. This enables us to see things like meta tags and scripts in snapshots.

**Code changes:**

- Adds new function called `renderWithHelmet` that is a wrapper around the `@testing-library/react` `render` method.

An example using the Chartbeat component in Simorgh

```jsx
const CanonicalChartbeatBeacon = ({ chartbeatConfig, chartbeatSource }) => {
  useEffect(() => {
    return () => {
      if (typeof window !== 'undefined' && window.pSUPERFLY) {
        /*
          This function is always called to update config values on page changes
          https://chartbeat.zendesk.com/hc/en-us/articles/210271287-Handling-virtual-page-changes
        */
        window.pSUPERFLY.virtualPage(chartbeatConfig);
      }
    };
  }, [chartbeatConfig]);

  return (
    <>
      <Helmet>
        <script async type="text/javascript">
          {`
        (function(){
          var _sf_async_config = window._sf_async_config = (window._sf_async_config || {});
          var config = ${JSON.stringify(chartbeatConfig)};
          for (var key in config) {
            _sf_async_config[key] = config[key];
          }
        })();
      `}
        </script>
        <script async type="text/javascript" src={chartbeatSource} />
      </Helmet>
      <h1>Hello I should be in the body</h1>
    </>
  );
};
```

would then render

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`CanonicalChartbeatAnalytics should return the helmet wrapper with the script snippet 1`] = `
<html>
  <head>
    <script
      async="true"
      type="text/javascript"
    >
      
        (function(){
          var _sf_async_config = window._sf_async_config = (window._sf_async_config || {});
          var config = {"domain":"test-domain","type":"article","sections":"section1 section2","chartbeatUID":1111,"virtualReferrer":null,"useCanonical":true,"title":"This is an article","uid":123};
          for (var key in config) {
            _sf_async_config[key] = config[key];
          }
        })();
      
    </script>
    <script
      async="true"
      src="//chartbeat.js"
      type="text/javascript"
    />
  </head>
  <body>
    <div>
      <h1>
        Hello I should be in the body
      </h1>
    </div>
  </body>
</html>
`;

```

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-12 12:09 UTC, dr3 requested changes
LGTM, just  some simple snapshot tests would be nice IMO as its more complicated

2019-09-12 12:09 UTC, dr3 commented on packages/utilities/psammead-test-helpers/src/index.js
> +const renderWithHelmet = async component => {
I know this file doesnt have tests, but as this is alot more complicated can you add some please?
Calling `shouldMatchSnapshot` a few times with various types of dummy components would be good. One with helmet, one with a fragment etc? We can use the snap it generates to assess its behavior?

2019-09-12 15:41 UTC, chris-hinds approved these changes

2019-09-12 16:01 UTC, ryanmccombe commented on packages/utilities/psammead-test-helpers/src/index.js
> + * Example of use in a test file:
This example is confusing - `renderHelmet` isn't exported

Isn't this `renderWithHelmet` function an internal helper for `shouldMatchSnapshot`?  It doesn't seem like it should be used like described here, or that it would work if it was.

2019-09-12 16:03 UTC, ryanmccombe approved these changes

2019-09-12 16:10 UTC, dr3 requested changes

2019-09-12 16:10 UTC, dr3 commented on packages/utilities/psammead-test-helpers/src/index.js
>      // select the first child to remove the pointless wrapping div from snapshots
This happens now :(

2019-09-12 16:10 UTC, dr3 commented on packages/utilities/psammead-test-helpers/__snapshots__/index.test.jsx.snap
> +  <body>
Any easy way to remove the body when not needed?

2019-09-12 16:26 UTC, jroebu14 commented on packages/utilities/psammead-test-helpers/__snapshots__/index.test.jsx.snap
> +  <body>
I'll look into it. Was worried about adding more complexity to an already complex looking function for not much value but it should be straightforward

2019-09-12 16:28 UTC, jroebu14 commented on packages/utilities/psammead-test-helpers/src/index.js
> + * Example of use in a test file:
Oh yeh. Code has changed and I forgot to update the comments. A good example of how commenting code can be a bad idea!

2019-09-12 16:31 UTC, jroebu14 commented on packages/utilities/psammead-test-helpers/src/index.js
>      // select the first child to remove the pointless wrapping div from snapshots
Are you worried about the async `it` callback? It won't affect the current test helper API.

2019-09-12 17:11 UTC, jroebu14 commented on packages/utilities/psammead-test-helpers/__snapshots__/index.test.jsx.snap
> +  <body>
I tried removing the body but that stopped other tests from rendering things in the body. I guess it breaks the renderer because it can't find the body element's div to put stuff in. I also tried this with removing just the div and it had the same effect :(

2019-09-12 17:15 UTC, jroebu14 commented on packages/utilities/psammead-test-helpers/src/index.js
> + * Example of use in a test file:
Is the comment looking ok now?

2019-09-12 17:48 UTC, pjlee11 commented
Jenkins is failing because this updates `packages/utilities/moment-timezone-include/package-lock.json` but doesn't bump the package version and changelog

2019-09-13 10:13 UTC, dr3 commented on packages/utilities/psammead-test-helpers/src/index.js
>      // select the first child to remove the pointless wrapping div from snapshots
Soz i meant `select the first child to remove the pointless wrapping div from snapshots` happens now

2019-09-13 10:17 UTC, jroebu14 commented on packages/utilities/psammead-test-helpers/src/index.js
>      // select the first child to remove the pointless wrapping div from snapshots
We still do when rendering components without helmet. I'll change the comments and var names.

2019-09-13 14:23 UTC, dr3 approved these changes
Soz for my confusion, looks great :)

2019-09-13 14:25 UTC, merged