Override moment relative timestamp translations - Sinhala, Thai, Ukrainian
BBC-archive/psammead pull request #2186
Opened 2019-09-19 13:11 UTC by OlgaLyubin

Resolves #2154 

**Overall change:** 
Override moment relative timestamps `psammead-locales` to have the correct translations for Sinhala, Thai and Ukrainian services.

**Code changes:**
Added Thai and Sinhala locales
Updated Ukrainian relative timestamp

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated jest tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

2019-09-20 07:14 UTC, dr3 approved these changes

2019-09-20 07:17 UTC, sadickisaac commented on packages/utilities/psammead-locales/moment/si.js
> +  postformat: null,
Do we need this?

2019-09-20 07:23 UTC, ghost requested changes
This is also supposed to handle the overriding of months for Ukrainian.
`января_февраля_марта_апреля_мая_июня_июля_августа_сентября_октября_ноября_декабря`

2019-09-23 09:55 UTC, OlgaLyubin commented
> This is also supposed to handle the overriding of months for Ukrainian.
> `января_февраля_марта_апреля_мая_июня_июля_августа_сентября_октября_ноября_декабря`

We do not need to override months for Ukrainian with these for now because those are Russian and are required for a Russian service.

2019-09-23 10:09 UTC, DenisHdz requested changes

2019-09-23 10:09 UTC, DenisHdz commented on packages/utilities/psammead-locales/moment/index.stories.jsx
> +import './gu';
Remove this line. `gu` is already imported above.

2019-09-23 10:09 UTC, DenisHdz commented on packages/utilities/psammead-locales/moment/index.stories.jsx
> +  { name: 'Gujarati', locale: 'gu' },
Same here.

2019-09-23 10:58 UTC, DenisHdz requested changes

2019-09-23 10:58 UTC, DenisHdz commented on packages/utilities/psammead-locales/moment/index.stories.jsx
> +import './sr';
Serbian is also imported twice.

2019-09-23 11:13 UTC, OlgaLyubin commented on packages/utilities/psammead-locales/moment/index.stories.jsx
> +import './sr';
All sorted now, thanks!

2019-09-23 11:17 UTC, DenisHdz approved these changes
Looks good :)

2019-09-23 12:23 UTC, ghost approved these changes

2019-09-24 13:47 UTC, paruchurisilpa commented
LGTM

2019-09-24 14:12 UTC, merged