Add stories in storybook for media icons in psammead-assets
BBC-archive/psammead pull request #2189
Opened 2019-09-19 14:09 UTC by EinsteinCarrey

Resolves #2158 

**Overall change:** _Add stories in psammead storybook for media icons SVGs in psammead-assets._

**Code changes:**

- _Group Brand svg in storybook._
- _Add media icons stories in storybook._

**Screenshots:**
![Screen Shot 2019-09-19 at 5 08 35 PM](https://user-images.githubusercontent.com/21374761/65251556-32c89580-db00-11e9-8b86-e936d17c579e.png)

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-20 07:36 UTC, ghost requested changes
Add `notes` to `Utilities|SVGs/MediaIcon Svgs`

2019-09-20 15:15 UTC, Bopchy approved these changes

2019-09-23 07:07 UTC, ghost approved these changes

2019-09-23 07:34 UTC, DenisHdz commented on packages/utilities/psammead-assets/src/svgs.stories.jsx
> +  'Utilities|SVGs/MediaIcon Svgs',
```suggestion
  'Utilities|SVGs/MediaIcons Svgs',
```

2019-09-23 08:37 UTC, j-pendlebury approved these changes
![](https://media.giphy.com/media/OjBocHTklyQda/giphy.gif)

2019-09-23 10:29 UTC, DenisHdz approved these changes

2019-09-23 10:34 UTC, merged