Create gel-foundations component and delete gel-constants and gel-foundations-styled-components
BBC-archive/psammead pull request #221
Opened 2018-12-17 14:44 UTC by dr3

Resolves #178 

Create gel-foundations component and delete gel-constants and gel-foundations-styled-components

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2018-12-17 15:39 UTC, ChrisBAshton requested changes
Looks good! Just a tweak or two

2018-12-17 15:39 UTC, ChrisBAshton commented on packages/utilities/gel-foundations/CHANGELOG.md
> +| 0.1.0   | [PR#XX](https://github.com/BBC-News/psammead/pull/XX) Create initial package, pulled in from gel-constants and gel-foundations-styled-components packages. |
```suggestion
| 0.1.0   | [PR#221](https://github.com/BBC-News/psammead/pull/221) Create initial package, pulled in from gel-constants and gel-foundations-styled-components packages. |

```

2018-12-17 15:39 UTC, ChrisBAshton commented on packages/utilities/gel-foundations/README.md
> +This package is a collection of variable constants which can be imported into your application.
```suggestion
This package is a collection of constants which can be imported into your application.
```

"variable constants" sounds like an oxymoron :-)

2018-12-17 16:19 UTC, ChrisBAshton approved these changes

2018-12-18 09:19 UTC, bcmn approved these changes
Approving -- This is going to conflict a whole bunch with my work on #212, so I'll block that ticket on this one.

2018-12-18 09:48 UTC, merged