Use @bbc/gel-foundations in Psammead
BBC-archive/psammead pull request #227
Opened 2018-12-18 11:33 UTC by radiocontrolled

Resolves https://github.com/BBC-News/psammead/issues/226

_PR changes summary to go here._

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2018-12-18 12:54 UTC, bcmn commented on packages/utilities/README.md
> +* [gel-foundations](./gel-foundations) - A range of styled-components and String constants for use in CSS, intended to help ensure GEL-compliance in components and other web-based projects in a consi
Ooops. Thank you for updating this! 🙌🏻

2018-12-18 12:55 UTC, bcmn submitted a review, later dismissed
Looks great!

2018-12-18 12:57 UTC, ChrisBAshton requested changes
Sorry!

2018-12-18 12:57 UTC, ChrisBAshton commented on packages/components/psammead-brand/CHANGELOG.md
> +| 0.1.2   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with[@bbc/gel-foundations in Psammead](https://github.com/BBC-
```suggestion
| 0.1.2   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with [@bbc/gel-foundations in Psammead](https://github.com/BBC-News/psammead/issues/226). |
```

2018-12-18 12:57 UTC, ChrisBAshton commented on packages/components/psammead-caption/CHANGELOG.md
> +| 0.1.1   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with[@bbc/gel-foundations in Psammead](https://github.com/BBC-
```suggestion
| 0.1.1   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with [@bbc/gel-foundations in Psammead](https://github.com/BBC-News/psammead/issues/226). |
```

2018-12-18 12:57 UTC, ChrisBAshton commented on packages/components/psammead-copyright/CHANGELOG.md
> +| 0.2.1   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with[@bbc/gel-foundations in Psammead](https://github.com/BBC-
```suggestion
| 0.2.1   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with [@bbc/gel-foundations in Psammead](https://github.com/BBC-News/psammead/issues/226). |
```

2018-12-18 12:57 UTC, ChrisBAshton commented on packages/components/psammead-headings/CHANGELOG.md
> +| 0.1.4   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with[@bbc/gel-foundations in Psammead](https://github.com/BBC-
```suggestion
| 0.1.4   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with [@bbc/gel-foundations in Psammead](https://github.com/BBC-News/psammead/issues/226). |
```

2018-12-18 12:57 UTC, ChrisBAshton commented on packages/components/psammead-paragraph/CHANGELOG.md
> +| 0.1.5   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with[@bbc/gel-foundations in Psammead](https://github.com/BBC-
```suggestion
| 0.1.5   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with [@bbc/gel-foundations in Psammead](https://github.com/BBC-News/psammead/issues/226). |
```

2018-12-18 12:57 UTC, ChrisBAshton commented on packages/components/psammead-sitewide-links/CHANGELOG.md
> +| 0.1.1   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with[@bbc/gel-foundations in Psammead](https://github.com/BBC-
```suggestion
| 0.1.1   | [PR#227](https://github.com/BBC-News/psammead/pull/227) Replace @bbc/gel-constants and @bbc/gel-foundations-styled-component with [@bbc/gel-foundations in Psammead](https://github.com/BBC-News/psammead/issues/226). |
```

2018-12-18 13:49 UTC, radiocontrolled commented
Changes applied @ChrisBAshton

2018-12-19 08:17 UTC, bcmn approved these changes
Looks even greater with that space. 😜

2018-12-19 09:41 UTC, ChrisBAshton approved these changes

2018-12-19 11:58 UTC, jamesbrumpton commented
LGTM

2018-12-19 12:43 UTC, merged