bumping dependencies
BBC-archive/psammead pull request #2318
Opened 2019-10-07 09:02 UTC by thekp

**Overall change:** _Bumping 3rd party dependencies_

**Code changes:**

bumping the following dependencies:
https://github.com/bbc/psammead/pull/2270
https://github.com/bbc/psammead/pull/2269
https://github.com/bbc/psammead/pull/2268
https://github.com/bbc/psammead/pull/2267
https://github.com/bbc/psammead/pull/2266
https://github.com/bbc/psammead/pull/2265
https://github.com/bbc/psammead/pull/2263
https://github.com/bbc/psammead/pull/2262
https://github.com/bbc/psammead/pull/2261
https://github.com/bbc/psammead/pull/2260
https://github.com/bbc/psammead/pull/2259
https://github.com/bbc/psammead/pull/2258
https://github.com/bbc/psammead/pull/2257

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

2019-10-07 10:00 UTC, jroebu14 approved these changes

2019-10-07 10:01 UTC, FK78 approved these changes
LGTM!

2019-10-07 10:02 UTC, FK78 reviewed
Snapshots need updating.

2019-10-07 10:56 UTC, FK78 requested changes
There are more dependabot issues.

2019-10-07 12:07 UTC, FK78 approved these changes

2019-10-07 15:16 UTC, ryanmccombe commented on packages/components/psammead-play-button/CHANGELOG.md
> +| 1.0.0-alpha.1 | [PR#2318](https://github.com/bbc/psammead/pull/2253) Update snapshot. |
```suggestion
| 1.0.0-alpha.1 | [PR#2318](https://github.com/bbc/psammead/pull/2318) Update snapshot. |
```

2019-10-07 15:16 UTC, ryanmccombe commented on CHANGELOG.md
> +| 1.8.15 | [PR#2318](https://github.com/bbc/psammead/pull/2298) Bumping 3rd party dependencies |
```suggestion
| 1.8.15 | [PR#2318](https://github.com/bbc/psammead/pull/2318) Bumping 3rd party dependencies |
```

2019-10-07 15:17 UTC, ryanmccombe approved these changes
Sick bumps

2019-10-08 13:15 UTC, paruchurisilpa commented
Looks good to me..

2019-10-08 16:17 UTC, merged