Image stretching fix
BBC-archive/psammead pull request #234
Opened 2018-12-19 12:44 UTC by sareh

Resolves #232

Fixes the stretching issue by making the height prop optional.

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2018-12-19 13:03 UTC, radiocontrolled commented on packages/components/psammead-image/CHANGELOG.md
> +| 0.2.0 | [PR#](https://github.com/BBC-News/psammead/pull/) Change height prop to be optional. Update the storybook example. |
```suggestion
 | 0.2.0 | [PR#234](https://github.com/BBC-News/psammead/pull/234) Change height prop to be optional. Update the storybook example. |
```

2018-12-19 13:21 UTC, ChrisBAshton requested changes
Can we update the README and make it clear the height is optional (and the implications for specifying it)? https://github.com/BBC-News/psammead/tree/latest/packages/components/psammead-image#usage

2018-12-19 13:21 UTC, ChrisBAshton commented on packages/components/psammead-image/CHANGELOG.md
> + | 0.2.0 | [PR#234](https://github.com/BBC-News/psammead/pull/234) Change height prop to be optional. Update the storybook example. |
```suggestion
| 0.2.0 | [PR#234](https://github.com/BBC-News/psammead/pull/234) Change height prop to be optional. Update the storybook example. |
```

2018-12-19 13:59 UTC, ChrisBAshton submitted a review, later dismissed

2018-12-19 13:59 UTC, ChrisBAshton commented on packages/components/psammead-image/README.md
> +The `height` prop is optional, since in some cases to preserve the image ratio we only want to specify the width and let the browser scale the image accordingly. However, in other cases the height mi
Nice 👏

2018-12-19 14:53 UTC, radiocontrolled submitted a review, later dismissed

2018-12-19 16:35 UTC, radiocontrolled approved these changes
🐻

2018-12-20 09:30 UTC, bcmn approved these changes

2018-12-20 09:52 UTC, ChrisBAshton approved these changes

2018-12-20 11:16 UTC, merged