Remove old Jalaali helpers in psammead-locales
BBC-archive/psammead pull request #2375
Opened 2019-10-10 14:45 UTC by HarveyPeachey

Resolves #2355 

**Overall change:** Removed Jalaali and string helpers in psammead-locales.

**Code changes:**

- Removed Jalaali helper from psammead-locales
- Removed `fa` locale override as this was only adding the Jalaali calendar

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-10-14 12:27 UTC, oluoluoxenfree approved these changes

2019-10-15 08:00 UTC, RayNjeri reviewed
Looks good so far but you may want to check on the drops on test coverage

2019-10-15 09:06 UTC, HarveyPeachey commented
> Looks good so far but you may want to check on the drops on test coverage

Yeah the reason for those drops is that I've removed those files so code climate shouldn't really be erroring.

2019-10-15 13:15 UTC, FK78 approved these changes

2019-10-15 13:17 UTC, ryanmccombe commented on packages/utilities/psammead-locales/CHANGELOG.md
> +| 2.24.0 | [PR#2375](https://github.com/bbc/psammead/pull/2300) Removed `fa` locale override and jalaali calendar helper  |
```suggestion
| 2.24.0 | [PR#2375](https://github.com/bbc/psammead/pull/2375) Removed `fa` locale override and jalaali calendar helper  |
```

2019-10-15 13:18 UTC, ryanmccombe approved these changes

2019-10-15 13:20 UTC, j-pendlebury approved these changes

2019-10-16 10:24 UTC, dr3 requested changes
Chatted IRL, should be a breaking change :)

2019-10-16 10:52 UTC, dr3 approved these changes

2019-10-16 12:22 UTC, jamesdonoh commented
Overriding CC total coverage change because it stems from the fact we are deleting code, not decreasing its coverage.

2019-10-16 12:22 UTC, merged