Use lerna bootstrap to hoist dependencies
BBC-archive/psammead pull request #239
Opened 2018-12-20 10:18 UTC by bcmn

Resolves #217, follows up on #121.

We can use `lerna bootstrap` to both install dependencies for all packages, & hoist common dependencies out of each nested package's `node_modules` & into the monorepo's `node_modules`. This hoisting is [recommended for lerna repos by styled-components](https://www.styled-components.com/docs/faqs#usage-with-lerna), & allows for the removal of the `clear-styled-components` script.

`lerna bootstrap` is configured to behave the same as our previous `postinstall` command -- running `npm ci`, instead of `npm install`, on all nested packages.

In doing this, I noticed many of the package-locks committed on `latest` are out of date. This PR fixes that.

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2018-12-20 10:27 UTC, ChrisBAshton submitted a review, later dismissed
Looks good to me 👍

2018-12-20 10:53 UTC, ChrisBAshton submitted a review, later dismissed

2018-12-20 11:03 UTC, sareh commented on packages/components/psammead-caption/package-lock.json
> +  "version": "0.1.1",
I'm surprised that the previous PRs didn't catch these. That's quite worrying! I wonder if the mismatched package/package-lock versions published on npm will cause `npm ci` to error. 
I suppose it'll be fixed next time we publish these packages to npm.

2018-12-20 11:03 UTC, sareh submitted a review, later dismissed
👍 Looks great.

2018-12-20 11:28 UTC, sareh submitted a review, later dismissed

2018-12-20 11:39 UTC, ChrisBAshton submitted a review, later dismissed

2018-12-20 12:32 UTC, sareh commented
Investigating why the Jenkins build is failing with this error:
```
npm ERR! Missing: @bbc/psammead-image@^0.1.0
```

I removed the `--ci` flag from the `postinstall` script and ran `npm install` locally.
This removed the `nanoid` package from the `package-lock.json`.  
After that, I returned the `--ci` flag and ran `npm install` again. It errored:
```
npm ERR! Missing: @bbc/psammead-image@^0.1.0
npm ERR! Missing: nanoid@^2.0.0
```
Need to investigate what exactly `lerna bootstrap` is doing under the hood to fix this issue.

2018-12-20 13:31 UTC, bcmn commented
Got it passing again, but not clear what the issue was. Going to scrutinise [the compare between the first fail & last pass](https://github.com/BBC-News/psammead/compare/853c39b...cc6494).

2019-01-02 12:00 UTC, bcmn commented
Resolved conflicting package-locks above -- Doing so simply seems to be a case of running `lerna exec -- npm install`. I don't believe this brakes the hoisting.

2019-01-02 14:02 UTC, dr3 approved these changes

2019-01-02 14:09 UTC, dr3 requested changes
This doesnt appear to be installing the modules correctly. I got a fresh clone, ran `npm i` and in the packages the node_modules arnt correct.

The only packages in the node_modules folder are bbc packages. Others, like styled-components arnt installed

2019-01-02 14:44 UTC, bcmn commented
> This doesnt appear to be installing the modules correctly. I got a fresh clone, ran npm i and in the packages the node_modules arnt correct.
> 
> The only packages in the node_modules folder are bbc packages. Others, like styled-components arnt installed

I think this is the understood behaviour of `--hoist`. There's more in [this link from the PR description](), but this seems relevant: 

> When the `--hoist` flag is used:
> 
> * Common dependencies will be installed _only_ to the top-level
>   `node_modules`, and omitted from individual package `node_modules`.
> * Mostly-common dependencies are still hoisted, but outlier packages
>   with different versions will get a normal, local `node_modules`
>   installation of the necessary dependencies.
>   * In this instance, `lerna bootstrap` will always use `npm install`
>     with the `--global-style` flag, regardless of client configuration.
> * Binaries from those common packages are symlinked to individual
>   package `node_modules/.bin` directories, so that `package.json`
>   scripts continue to work unmodified.
> * Well-behaved Node-based software should continue to work unmodified.

I suspect most of our dependencies are "common" or "mostly common".

2019-01-02 15:17 UTC, dr3 submitted a review, later dismissed
Hmm ok the hoisting seems to be working, curious what issues might arise, but cant see any atm, lets see how it goes.

2019-01-03 09:41 UTC, ChrisBAshton commented
I ran an `npm install`and I have a `node_modules/@bbc/psammead-image` folder.

My `package-lock.json` also has removed `@bbc/psammead-image` (around line 993).

Not sure why `@bbc/psammead-image` is being treated differently to our other components 🤔 For example, it's used as a devDependency in ` @bbc/psammead-figure`. But `@bbc/psammead-test-helpers` is also a dev dependency of the same module, and _it_ isn't in `node_modules`. I would have expected `@bbc/psammead-image` to be hoisted & `npm link`ed like everything else...?

2019-01-03 12:28 UTC, dr3 commented
This issue doesn't happen with --force-local IMO we should use this for the time being, and file an issue with lerna to try and fix this bug.

2019-01-03 14:32 UTC, bcmn commented
It's been agreed that we'll use `--force-local` to get this PR merged, & open an issue with Lerna to document some quirks we've observed with their semver range comparisons. The goal is to remove the flag once these quirks have been fixed and/or explained adequately.

2019-01-03 14:44 UTC, dr3 submitted a review, later dismissed

2019-01-04 11:26 UTC, bcmn commented
Following up on my last comment, & this comment, following discussion in [another place](https://en.wikipedia.org/wiki/Another_place):

> I ran an `npm install`and I have a `node_modules/@bbc/psammead-image` folder.
> 
> My `package-lock.json` also has removed `@bbc/psammead-image` (around line 993).
> 
> Not sure why `@bbc/psammead-image` is being treated differently to our other components 🤔 For example, it's used as a devDependency in ` @bbc/psammead-figure`. But `@bbc/psammead-test-helpers` is also a dev dependency of the same module, and _it_ isn't in `node_modules`. I would have expected `@bbc/psammead-image` to be hoisted & `npm link`ed like everything else...?

It's important to be clear about what the scenario was here:

- [`lerna bootstrap` will symlink together packages which are dependencies of each other, so long as the semver range matches.](https://github.com/lerna/lerna/tree/master/commands/bootstrap#readme) If it doesn't match, it will install the requested version into `node_modules`.
- `psammead-image` has a committed version of `0.2.1`.
- `psammead-figure` has a dependency on `psammead-image`, with a range of `^0.1.0`.
- NPM's caret range syntax is defined as ["allowing changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple"](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004). More detailed examples are available in their documentation.
- This is based on [item 4 of Semantic Versioning 2.0.0](https://semver.org/#spec-item-4), which treats _anything_ under 1.0.0 as a potentially breaking change.

As such, this is the correct behaviour -- If `psammead-image` had a version of `0.1.x`, it would be symlinked to the repo version. However, by changing to `0.2.x`, we have exceeded the range specified by `^0.1.0`.

As such, I don't intend to open additional issues on this point. We'll discuss whether we want to keep the `--force-local` flag separately.

2019-01-04 12:14 UTC, dr3 approved these changes
LGTM

2019-01-04 17:03 UTC, pjlee11 approved these changes
Great work 😎

2019-01-07 09:51 UTC, jamesbrumpton commented
LGTM 👍

2019-01-07 09:54 UTC, merged