chore: remove react-test-renderer from package.jon
BBC-archive/psammead pull request #2405
Opened 2019-10-15 13:46 UTC by mykeels

Resolves #774

**Overall change:** _Remove reference to react-test-renderers._

**Code changes:**

- _Remove react-test-renderer from package.json._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-10-15 14:57 UTC, EinsteinNjoroge approved these changes

2019-10-16 07:11 UTC, rhenshaw56 requested changes
I think we may need to remove [references to it here](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-test-helpers/README.md#exported-functions) as well, maybe reword the readme a bit

2019-10-16 10:17 UTC, rhenshaw56 approved these changes

2019-10-16 10:57 UTC, amywalker1987 commented
`Branch must update CHANGELOG.md in psammead-test-helpers

Branch must update package-lock.json in psammead-test-helpers

Branch must update package.json in psammead-test-helpers`

2019-10-17 11:09 UTC, mykeels commented
I'll be closing this PR, because I can't update the branch.  I've open a [duplicate PR from a fork](https://github.com/bbc/psammead/pull/2423).

2019-10-17 11:10 UTC, closed without merging