Rm react test renderer
BBC-archive/psammead pull request #2423
Opened 2019-10-17 11:07 UTC by mykeels

Resolves https://github.com/bbc/psammead/issues/774

Duplicate of https://github.com/bbc/psammead/pull/2405

**Overall change:** _Remove reference to react-test-renderers._

**Code changes:**

- _Remove react-test-renderer from package.json._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-10-17 11:13 UTC, thekp requested changes
Your merge latest into this branch seems to have messed up your changelog changes so you will need to bump the package.json version/update changelog again :/

2019-10-17 11:17 UTC, EinsteinNjoroge approved these changes

2019-10-17 11:45 UTC, rhenshaw56 approved these changes
LGTM! the changelog needs a modification

2019-10-17 11:45 UTC, rhenshaw56 commented on CHANGELOG.md
> +| 1.8.21 | [PR#2405](https://github.com/bbc/psammead/pull/2405) Remove react-test-renderer |
:eyes:

2019-10-18 08:17 UTC, mykeels commented
The only change to the psammead-test-helpers package, was to the README file. Does this still require a version bump? @thekp @rhenshaw56

2019-10-18 09:10 UTC, thekp approved these changes
![](https://media.giphy.com/media/h3uCITmuLW8Cbaf67I/giphy.gif)

2019-10-22 10:53 UTC, FK78 requested changes
Need to bump these dependencies before merging.

2019-10-22 10:53 UTC, FK78 commented on package.json
> +    "@babel/core": "^7.6.2",
You've downgraded the dependency, it was bumped in this PR #2452.

2019-10-22 10:53 UTC, FK78 commented on package.json
> +    "lerna": "^3.17.0",
You've downgraded the dependency, it was bumped in this PR #2452.

2019-10-22 10:56 UTC, closed without merging