guidance icon
BBC-archive/psammead pull request #2531
Opened 2019-10-30 13:25 UTC by rhenshaw56

Resolves https://github.com/bbc/psammead/issues/2529
part of https://github.com/bbc/psammead/pull/2517

**Overall change:** adds guidance icon

**Code changes:**

- adds guidance icon
---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-10-30 14:32 UTC, 12 commented on packages/utilities/psammead-assets/CHANGELOG.md
> +| 2.7.0 | [PR#2433](https://github.com/bbc/psammead/pull/2531) Added Guidance icon |
```suggestion
| 2.7.0 | [PR#2531](https://github.com/bbc/psammead/pull/2531) Added Guidance icon |
```

2019-10-30 14:54 UTC, 12 approved these changes

2019-10-30 14:58 UTC, dr3 submitted a review, later dismissed

2019-10-30 14:58 UTC, dr3 commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +  width: 1.5rem;
Can you use gel spacings here please? :)

2019-10-30 15:04 UTC, simonsinclair requested changes
Thanks for adding this, @rhenshaw56. I've left a few comments below.

2019-10-30 15:04 UTC, simonsinclair commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +      <g>
This grouping `<g></g>` is unneeded and can be pruned safely.

2019-10-30 15:04 UTC, simonsinclair commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +        <circle fill="inherit" cx="22" cy="22" r="11" />
`fill="inherit"` is redundant here and can be pruned safely.

2019-10-30 15:04 UTC, simonsinclair commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +      width="35px"
I can't think of a scenario where we'd have an odd width and height as this would create one pixel of oddness in our layouts. This is overridden by the style, but I would set both of these to `24px` to be perfectly safe.

2019-10-30 15:54 UTC, simonsinclair reviewed
The changes look good, thanks.

My only concern is around how much inherent space this icon brings with it. This is space we won't get back within our document. Is it worth someone from UX reviewing this PR and/or supplying an icon that is clipped to the artwork like the audio icon (pictured) and our others?

<img width="309" alt="Screenshot 2019-10-30 at 15 49 37" src="https://user-images.githubusercontent.com/1430787/67874683-2be46800-fb2d-11e9-897c-3778b4a18c52.png">
<img width="320" alt="Screenshot 2019-10-30 at 15 48 35" src="https://user-images.githubusercontent.com/1430787/67874684-2be46800-fb2d-11e9-8920-6aff0ddc61ef.png">

2019-10-30 17:42 UTC, simonsinclair commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +    </GuidanceIcon>
This asset is much better, but please can you apply the previous optimisations?

```
<GuidanceIcon
  viewBox="0 0 24 24"
  focusable="false"
  height="24px"
  width="24px"
>
  <path d="M24,12 C24,18.627 18.627,24 12,24 C5.3715,24 0,18.627 0,12 C0,5.373 5.3715,0 12,0 C18.627,0 24,5.373 24,12" />
  <path
    fill={C_WHITE}
    d="M17.515275,17.99265 L15.500775,17.99265 L15.316275,16.6839 C14.493525,17.8419 13.084275,18.24465 11.975025,18.24465 C8.349525,18.24465 5.999775,15.4749 5.999775,12.00015 C5.999775,8.5254 8.349525,5.75565 11.975025,5.75565 C14.459775,5.75565 17.112525,7.08165 17.398275,10.08615 L14.275275,10.08615 C14.174025,9.06315 13.167525,8.44215 11.907525,8.44215 C9.893775,8.44215 9.122025,10.2204 9.122025,12.00015 C9.122025,13.7799 9.893775,15.55965 11.907525,15.55965 C13.453275,15.55965 14.493525,14.8374 14.661525,13.74615 L12.479025,13.74615 L12.479025,11.4294 L17.515275,11.4294 L17.515275,17.99265 Z"
  />
</GuidanceIcon>
```

2019-10-30 17:47 UTC, simonsinclair requested changes

2019-10-30 17:47 UTC, simonsinclair commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +    <GuidanceIcon
This asset is much better, but needs the prior optimisations:
- No group element
- No fixed colour fills apart from the "G", which should be `C_WHITE`.

2019-10-30 17:47 UTC, simonsinclair commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +        <path
Why is the circle a `<path />` and not a `<circle />`?

2019-10-31 08:36 UTC, rhenshaw56 commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +    <GuidanceIcon
@simonsinclair i've made the adjustments, I set the "G" to be `C_EBON` as it's dark from the designs and the path for the circle around to `C_WHITE`

2019-10-31 08:36 UTC, rhenshaw56 commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +        <path
@simonsinclair that's what I got from ux

2019-10-31 09:31 UTC, simonsinclair requested changes

2019-10-31 09:31 UTC, simonsinclair commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +        fill={C_EBON}
This should be `C_WHITE`. The circle is the "path" above.

2019-10-31 09:31 UTC, simonsinclair commented on packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
> +        fill={C_WHITE}
`fill=""` isn't needed here, because it inherits the colour from the parent style.

2019-10-31 10:41 UTC, simonsinclair approved these changes

2019-10-31 10:48 UTC, jroebu14 approved these changes
LGTM

2019-10-31 10:53 UTC, merged