Bump psammead-test-helpers version
BBC-archive/psammead pull request #255
Opened 2019-01-03 15:46 UTC by bcmn

Resolves #N/A

![screenshot 2019-01-03 at 15 30 43](https://user-images.githubusercontent.com/11646957/50646424-e804ee80-0f6d-11e9-9296-0f2c6024abe8.png)

In viewing the `psammead-test-helpers` package on NPM, I noticed the latest version has a different version to what is defined in the `package.json` (see above), & the history doesn't even include the current value in the `package.json`. 🤯 It looks like it was published in error from a branch. This PR bumps the version higher than that on NPM.

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-01-03 15:49 UTC, dr3 requested changes
Apologies for this, we should update the changelog saying why the sudden bump

2019-01-03 16:12 UTC, dr3 commented on packages/utilities/psammead-test-helpers/CHANGELOG.md
> +| 0.1.2   | [PR#255](https://github.com/BBC-News/psammead/pull/255) Bumps package version to fix what appears to be an erroneously-published version. |
```suggestion
| 0.2.1   | [PR#255](https://github.com/BBC-News/psammead/pull/255) Bumps package version to fix what appears to be an erroneously-published version. |
```

2019-01-03 18:18 UTC, dr3 commented on packages/utilities/psammead-test-helpers/CHANGELOG.md
> +| 0.1.2   | [PR#255](https://github.com/BBC-News/psammead/pull/255) Bumps package version to fix what appears to be an erroneously-published version. |
LGTM after this

2019-01-04 10:18 UTC, dr3 approved these changes

2019-01-04 10:43 UTC, ChrisBAshton approved these changes

2019-01-04 11:38 UTC, merged