Grid negative margins
BBC-archive/psammead pull request #2568
Opened 2019-11-05 15:30 UTC by sareh

Part of https://github.com/bbc/simorgh/issues/3686

Necessary for this 'use Psammead Grid in Simorgh' PR: https://github.com/bbc/simorgh/pull/4493

**Overall change:** Add enableNegativeGelMargins prop, to enable fullscreen Grid within an outer Grid that has `enableGelMargins`

This usecase is important for an article that needs Margins enabled, but that might have an image within that page that does not have margins (is full-bleed).

**Code changes:**

- Add enableNegativeGelMargins prop
- Add story for this prop.

http://localhost:8180/?path=/story/components-grid--example-with-enablenegativegelmargins-on-the-image-grid
<img width="913" alt="Screenshot of storybook example" src="https://user-images.githubusercontent.com/3028997/68221274-18c81100-ffe1-11e9-84a7-292474104145.png">

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-11-05 15:42 UTC, jroebu14 approved these changes
Looks good

2019-11-05 16:03 UTC, DenisHdz requested changes
We also need to add that condition to the fallbacks to make it work on IE.

<img width="1291" alt="ie-enablenegativemargins" src="https://user-images.githubusercontent.com/46446236/68223962-b0c7f980-ffe5-11e9-8705-f291e08d615c.png">

2019-11-13 11:43 UTC, sareh commented
There is a lot of complexity in the fallbacks. @DenisHdz & I have discussed to merge this in now without the fallbacks, since this is an alpha version and then add fallbacks in a future PR: https://github.com/bbc/psammead/pull/2621

2019-11-13 11:49 UTC, DenisHdz approved these changes

2019-11-13 11:50 UTC, merged