Explicitly set h1 styles display and font weight
BBC-archive/psammead pull request #2575
Opened 2019-11-06 15:53 UTC by pjlee11

Related to xxx

**Overall change:** Explicitly adds `font-weight: 500` and `display: block` which are defaults on `<h1>`, so that we can use this component `as="strong"` for the `OnScreenHeadline`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated jest tests added (for new features) or updated (for existing features)
- ~[ ] This PR requires manual testing~

2019-11-06 16:33 UTC, dr3 requested changes

2019-11-06 16:33 UTC, dr3 commented on packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
>    font-weight: 700;
:O

2019-11-06 16:37 UTC, pjlee11 commented on packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
>    font-weight: 700;
Nothing to see here .... pushed changes

2019-11-06 16:38 UTC, dr3 approved these changes

2019-11-07 16:10 UTC, ryanmccombe approved these changes

2019-11-07 16:10 UTC, 12 approved these changes

2019-11-07 16:40 UTC, merged