Add navigation icons to psammead-assets
BBC-archive/psammead pull request #2581
Opened 2019-11-07 14:57 UTC by OlgaLyubin

Resolves #NUMBER

**Overall change:** 
Added hamburger and cross icons which will be used in new Navigation Iteration.

**Code changes:**
- Added svgs for hamburger and cross icons
- Added stories for navigation icons

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-11-07 17:19 UTC, FK78 approved these changes
LGTM!

2019-11-08 07:42 UTC, rhenshaw56 approved these changes

2019-11-08 09:39 UTC, DenisHdz requested changes
If a Firefox user sets the background to white in High Contrast mode, the icon won't be visible.
Can you replace it with currentColor as we do with the MediaIcons?

```
import React from 'react';
import styled from 'styled-components';

const MenuIcon = styled.svg`
  color: #FFF;
  fill: currentColor;
`;

const navigationIcons = {
  hamburger: (
    <MenuIcon width={44} height={44}>
      <path
        d="M12 29h21v-2.333H12V29zm0-5.833h21v-2.334H12v2.334zM12 15v2.333h21V15H12z"

      />
    </MenuIcon>
  ),
  cross: (
    <MenuIcon width={44} height={44}>
      <path
        d="M26.741 15L21.6 20.142 16.458 15 15 16.458l5.142 5.142L15 26.742l1.458 1.458 5.142-5.141 5.141 5.141 1.459-1.458-5.142-5.142 5.142-5.142z"
        fillRule="evenodd"
      />
    </MenuIcon>
  ),
};

export default navigationIcons;
```

2019-11-08 13:31 UTC, DenisHdz approved these changes
LGTM 💯

2019-11-11 09:46 UTC, sareh requested changes
Looks great. Just one point regarding width/height values.

2019-11-11 09:46 UTC, sareh commented on packages/utilities/psammead-assets/src/svgs/navigationIcons.jsx
> +    <MenuIcon width={44} height={44}>
Width and height properties should have units associated with them.
```suggestion
    <MenuIcon width="44px" height="44px">
```

2019-11-11 09:46 UTC, sareh commented on packages/utilities/psammead-assets/src/svgs/navigationIcons.jsx
> +    <MenuIcon width={44} height={44}>
```suggestion
    <MenuIcon width="44px" height="44px">
```

2019-11-11 09:56 UTC, sareh approved these changes
👍 Looks great.

2019-11-11 11:58 UTC, jamesbrumpton commented
lgtm

2019-11-11 12:02 UTC, merged