Change yeoman generator
BBC-archive/psammead pull request #2611
Opened 2019-11-12 13:23 UTC by oluoluoxenfree

Resolves #2188 

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-11-15 11:46 UTC, mykeels commented
Went with yeoman's list functionality.

![image](https://user-images.githubusercontent.com/11996508/68941331-dbfcd680-07a5-11ea-9c1d-95d3cb546a14.png)

2019-11-15 15:17 UTC, chris-hinds reviewed
should this be including new templates for the new package types?

2019-11-19 10:43 UTC, mykeels commented
@hindsc52 I've created [this issue](https://github.com/bbc/psammead/issues/2642), and its linked PR to track adding unique templates for package types.

2019-11-19 11:45 UTC, hotinglok requested changes
It seems like the condition to stop people from creating packages of the same name doesn't work the same way for `containers` and `utilities` as it does for `components`. In components, a prompt stops you immediately if you enter a package with the same name as an existing one whereas for the new templates, it lets you carry on with the whole process only asking at the end if you would like to overwrite the existing package. I think it should be updated for consistency.

2019-11-20 08:47 UTC, mykeels commented
@lokh01 this should work now.

2019-11-20 15:20 UTC, lokh01 commented on .yeoman/src/get-existing/index.js
> +module.exports  = getExistingPackages;
```suggestion
module.exports = getExistingPackages;
```

2019-11-20 15:20 UTC, lokh01 commented on .yeoman/src/get-existing/index.js
> +          .reduce((arr, item) => arr.concat(item))
Remove extra tab space

2019-11-20 15:21 UTC, hotinglok approved these changes
Besides linting issues, the functionality is fine now so it looks good to me on that front. Just need to clean up some of the files.

2019-11-22 05:54 UTC, mykeels commented on .yeoman/src/get-existing/index.js
> +module.exports  = getExistingPackages;
Fixed!

2019-11-22 05:54 UTC, mykeels commented
Fixed linting issues.

2019-11-27 08:18 UTC, j-pendlebury approved these changes
LGTM 👍

2019-11-27 08:34 UTC, merged