Fix failing Unit Test in Psammead timestamp container
BBC-archive/psammead pull request #2612
Opened 2019-11-12 13:54 UTC by FK78

Resolves #2570

**Overall change:** _Add conditional statements to check if we are in DST.)

**Code changes:**

- _Added an `if` and `else` conditional statement._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-11-12 13:59 UTC, thekp requested changes
i think you'll have to update the package.json/changelog/package-lock

2019-11-12 14:07 UTC, thekp approved these changes

2019-11-12 15:27 UTC, thekp approved these changes
![](https://media.giphy.com/media/eMeMQ0Y4DHS2k/giphy.gif)
LGTM

2019-11-12 17:14 UTC, EinsteinNjoroge requested changes

2019-11-12 17:14 UTC, EinsteinNjoroge commented on packages/containers/psammead-timestamp-container/src/timestampUtilities.test.js
> +    expect(allButAMonth.fromNow()).toEqual('a month ago');
This test is still failing

2019-11-13 12:24 UTC, EinsteinNjoroge approved these changes

2019-11-13 14:56 UTC, jamesdonoh approved these changes

2019-11-13 16:10 UTC, jroebu14 approved these changes

2019-11-13 16:18 UTC, merged