Increase viewport of the 1 column most read list, add timestamp spacing
BBC-archive/psammead pull request #2936
Opened 2020-01-14 15:12 UTC by thekp

Resolves #NUMBER

**Overall change:** _Make the 1 column most read version to appear on `GEL_GROUP_2_SCREEN_WIDTH_MAX`, add spacing between link and timestamp_

**Code changes:**

- _Added a wrapper for timestamp component which adds a padding-top of 8px._
- _After discussion with Natalie, it was suggested to increase the viewport of the 1 column most read version to `GEL_GROUP_2_SCREEN_WIDTH_MAX`_

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2020-01-17 13:10 UTC, Bopchy commented on packages/components/psammead-most-read/CHANGELOG.md
> +| 0.5.1-alpha.4 | [PR#2936](https://github.com/bbc/psammead/pull/2933) Increase 1 column viewport to MAX_GEL_GROUP_2, add spacing between timestamp and link and add padding-top to link |
```suggestion
| 0.5.1-alpha.4 | [PR#2936](https://github.com/bbc/psammead/pull/2936) Increase 1 column viewport to MAX_GEL_GROUP_2, add spacing between timestamp and link and add padding-top to link |
```

2020-01-17 13:11 UTC, thekp commented on packages/components/psammead-most-read/CHANGELOG.md
> +| 0.5.1-alpha.4 | [PR#2936](https://github.com/bbc/psammead/pull/2933) Increase 1 column viewport to MAX_GEL_GROUP_2, add spacing between timestamp and link and add padding-top to link |
thank you 👍

2020-01-17 13:39 UTC, Bopchy approved these changes
LGTM 👍

2020-01-20 09:07 UTC, DenisHdz requested changes

2020-01-20 09:07 UTC, DenisHdz commented on packages/components/psammead-most-read/src/Item/index.jsx
> +  padding-top: 6px;
Can this be in `rem` and defined as a constant?

2020-01-20 10:35 UTC, DenisHdz commented on packages/components/psammead-most-read/src/Item/index.jsx
> +const alignRankToLinkSpacing = '0.375rem';
Just for consistency:

```suggestion
const ALIGN_RANK_TO_LINK_SPACING = '0.375rem';
```

2020-01-20 10:36 UTC, thekp commented on packages/components/psammead-most-read/src/Item/index.jsx
> +  padding-top: ${alignRankToLinkSpacing};
```suggestion
  padding-top: ${ALIGN_RANK_TO_LINK_SPACING};
```

2020-01-20 10:59 UTC, DenisHdz approved these changes
LGTM

2020-01-20 11:44 UTC, merged