Move skip link top so it fits within brand banner
BBC-archive/psammead pull request #2946
Opened 2020-01-16 16:10 UTC by tochwill

Resolves #2944

**Overall change:** Move skip to content link top value to stay within brand banner height <400px.

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2020-01-16 16:11 UTC, tochwill commented on packages/components/psammead-brand/CHANGELOG.md
> +| 5.1.4 | [PR#XXXX](https://github.com/bbc/psammead/pull/XXXX) Move skip to content link top to stay within brand banner height |
```suggestion
| 5.1.4 | [PR#2946](https://github.com/bbc/psammead/pull/2946) Move skip to content link top to stay within brand banner height |
```

2020-01-16 16:20 UTC, DenisHdz approved these changes
Thanks for the fix 👍

2020-01-16 16:21 UTC, DenisHdz requested changes
You have to bump the `package-lock.json` too.

2020-01-16 16:38 UTC, AlistairGempf approved these changes
Looks good

2020-01-16 16:38 UTC, DenisHdz approved these changes

2020-01-20 15:44 UTC, paruchurisilpa commented
Looks good to me..

2020-01-22 09:54 UTC, tochwill commented
Just need to update package.json etc after resolving conflicts in the changelog

2020-01-22 10:42 UTC, merged