Spacing updates on the Story Promo List and Section Label
BBC-archive/psammead pull request #3058
Opened 2020-02-04 17:06 UTC by DenisHdz

Resolves https://github.com/bbc/psammead/issues/3055

**Overall change:**
Update Story Promo List and Section Label spacings, raised as a part of the Desktop Front Page UX review.

**Code changes:**
- Update `StoryPromoList` padding-top to 0 above 1008px
- Add a margin-top of 1.5rem to the `SectionLabel` above 1008px

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2020-02-04 17:29 UTC, sareh requested changes
These changes look good. My only concern is having these changes as patch versions - they'll be pulled into Simorgh and then spacing between items on the existing layout will be suboptimal:

e.g. this is what the section label change will be like: 
<img width="826" alt="Screenshot 2020-02-04 at 17 20 05" src="https://user-images.githubusercontent.com/3028997/73769539-bb279a00-4772-11ea-9f05-958a0a02b3ae.png">

And this is what the Story Promo List changes will look like with the single-column layout - this page will have the headline text intersecting the keyline between promos.
<img width="815" alt="Screenshot 2020-02-04 at 17 26 42" src="https://user-images.githubusercontent.com/3028997/73770016-967ff200-4773-11ea-9179-9862124756af.png">

We should consider making these a breaking change so they don't automatically get pulled in.

2020-02-05 08:35 UTC, DenisHdz commented
> These changes look good. My only concern is having these changes as patch versions - they'll be pulled into Simorgh and then spacing between items on the existing layout will be suboptimal:
> 
> e.g. this is what the section label change will be like:
> <img alt="Screenshot 2020-02-04 at 17 20 05" width="826" src="https://user-images.githubusercontent.com/3028997/73769539-bb279a00-4772-11ea-9f05-958a0a02b3ae.png">
> 
> And this is what the Story Promo List changes will look like with the single-column layout - this page will have the headline text intersecting the keyline between promos.
> <img alt="Screenshot 2020-02-04 at 17 26 42" width="815" src="https://user-images.githubusercontent.com/3028997/73770016-967ff200-4773-11ea-9179-9862124756af.png">
> 
> We should consider making these a breaking change so they don't automatically get pulled in.

Thanks for flagging this, I've bumped them to a major version 👍

2020-02-05 09:18 UTC, sareh approved these changes
👍 Thanks for the update. Looks good!

2020-02-05 15:28 UTC, OlgaLyubin approved these changes
Looks good to me

2020-02-05 16:36 UTC, merged