Update InlineLink styling
BBC-archive/psammead pull request #309
Opened 2019-02-25 15:35 UTC by bcmn

Resolves #286 

**Overall change:** Changes the InlineLink appearance to match the updated Simorgh designs.

**Code changes:**

- Updates InlineLink colours, bumping psammead-styles dependency.
- Currently doesn't alter underline implementation -- we wanted to avoid using `border-bottom`, but UX have specified specific pixel stylings depending on hover/visited state. 🤔

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests ~added~ updated for new features
- [ ] Test engineer approval

2019-02-26 13:58 UTC, sareh requested changes

2019-02-26 13:58 UTC, sareh commented on packages/components/psammead-inline-link/CHANGELOG.md
> +| 0.3.0   |  |
Could you please update the changelog here?

2019-02-26 13:58 UTC, sareh commented on packages/components/psammead-inline-link/package.json
> +  "version": "0.3.0",
Please update the `package-lock.json` too.

2019-02-26 14:02 UTC, sareh commented on packages/components/psammead-inline-link/package.json
> +  "version": "0.3.0",
The comment under the `roadmap` can likely be removed, too: https://github.com/bbc/psammead/blob/latest/packages/components/psammead-inline-link/README.md#roadmap

2019-02-26 14:17 UTC, sareh approved these changes
👍 Looks great! Thanks for making the changes.

2019-02-26 15:23 UTC, pjlee11 approved these changes
LGTM 👍

2019-02-27 10:18 UTC, jamesbrumpton commented
👍

2019-02-27 10:29 UTC, merged