Move to storybook 5
BBC-archive/psammead pull request #323
Opened 2019-03-05 21:16 UTC by dr3

Resolves #NUMBER

**Overall change:** Move to storybook 5

**Code changes:**

- Swap the readme addon for the notes one
- Update webpack config

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-03-11 08:29 UTC, dr3 commented on .storybook/config.js
> +    'https://user-images.githubusercontent.com/11341355/54079666-af202780-42d8-11e9-9108-e47ea27fddc5.png',
I have added this as without it you lose the word 'Psammead' from the top left

2019-03-11 10:02 UTC, sareh requested changes
This looks great locally. ✨ I've just added some comments about updating links in Readmes and tidying up the notes implementation.

2019-03-11 10:02 UTC, sareh commented on packages/components/psammead-brand/src/index.stories.jsx
>  import React from 'react';
At the top of each README.md file, we link to the Storybook URL e.g. https://bbc.github.io/psammead/?selectedKind=Brand  In Storybook v5, the URL structure changes, so will need to be updated to this format: 
https://bbc.github.io/psammead/?path=/info/brand--default

2019-03-11 10:02 UTC, sareh commented on .storybook/config.js
> +    sortStoriesByKind: true,
```suggestion
```
This does not appear to be sorting the stories. Likely due to the value of the separator not being added. Removing this parameter retains this order:

<img width="208" alt="Screen Shot storybook menu" src="https://user-images.githubusercontent.com/3028997/54114075-7fa91200-43e1-11e9-9692-e934bf535b64.png">

2019-03-11 10:02 UTC, sareh commented on .storybook/config.js
>  const GlobalStyle = createGlobalStyle`
I checked that Global Styles are loading correctly & that the AMP Decorator is loading for the AMP image component. 👍 All working great.

2019-03-11 10:02 UTC, sareh commented on packages/components/psammead-brand/src/index.stories.jsx
>  import Readme from '../README.md';
```suggestion
import notes from '../README.md';
```
By changing the name of the import, we could tidy up the notes declaration below.

2019-03-11 10:02 UTC, sareh commented on packages/components/psammead-brand/src/index.stories.jsx
> +  { notes: Readme },
```suggestion
  { notes },
```

2019-03-11 10:02 UTC, sareh commented on packages/components/psammead-brand/src/index.stories.jsx
>  import React from 'react';
To ensure the Readme updates are pushed up to npm, we'll need to bump all of the package versions. Please note updating them in `package.json` and `package-lock.json` as well as adding notes in the `CHANGELOG.md`

2019-03-11 10:22 UTC, dr3 commented on packages/components/psammead-brand/src/index.stories.jsx
>  import Readme from '../README.md';
Done :)

2019-03-11 10:22 UTC, dr3 commented on packages/components/psammead-brand/src/index.stories.jsx
> +  { notes: Readme },
Done :)

2019-03-11 10:22 UTC, dr3 commented on .storybook/config.js
> +    sortStoriesByKind: true,
Done :)

2019-03-11 11:07 UTC, dr3 commented on packages/components/psammead-brand/src/index.stories.jsx
>  import React from 'react';
Done :)

2019-03-11 12:34 UTC, sareh commented on packages/components/psammead-caption/README.md
> +# psammead-caption - [![Storybook](https://raw.githubusercontent.com/storybooks/brand/master/badge/badge-storybook.svg?sanitize=true)](https://bbc.github.io/psammead/?path=/story/caption--default) [!
```suggestion
# psammead-caption - [![Storybook](https://raw.githubusercontent.com/storybooks/brand/master/badge/badge-storybook.svg?sanitize=true)](https://bbc.github.io/psammead/?path=/story/brand--default) [![GitHub license](https://img.shields.io/badge/license-Apache%202.0-blue.svg)](https://github.com/BBC/psammead/blob/latest/LICENSE) [![npm version](https://img.shields.io/npm/v/@bbc/psammead-caption.svg)](https://www.npmjs.com/package/@bbc/psammead-caption) [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](https://github.com/BBC/psammead/blob/latest/CONTRIBUTING.md)
```

2019-03-11 12:39 UTC, sareh commented on packages/components/psammead-sitewide-links/package.json
> +  "version": "0.3.1s",
```suggestion
  "version": "0.3.1",
```

2019-03-11 12:39 UTC, sareh commented on packages/components/psammead-sitewide-links/package-lock.json
> +  "version": "0.3.1s",
```suggestion
  "version": "0.3.1",
```

2019-03-11 12:41 UTC, sareh commented on packages/components/psammead-brand/README.md
> +# psammead-brand - [![Storybook](https://raw.githubusercontent.com/storybooks/brand/master/badge/badge-storybook.svg?sanitize=true)](https://bbc.github.io/psammead/?path=/info/imageplaceholder--defau
```suggestion
# psammead-brand - [![Storybook](https://raw.githubusercontent.com/storybooks/brand/master/badge/badge-storybook.svg?sanitize=true)](https://bbc.github.io/psammead/?path=/story/brand--default) [![GitHub license](https://img.shields.io/badge/license-Apache%202.0-blue.svg)](https://github.com/bbc/psammead/blob/latest/LICENSE) [![npm version](https://img.shields.io/npm/v/@bbc/psammead-brand.svg)](https://www.npmjs.com/package/@bbc/psammead-brand) [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](https://github.com/bbc/psammead/blob/latest/CONTRIBUTING.md)
```

2019-03-11 12:43 UTC, sareh submitted a review, later dismissed
👍 Looks great!

2019-03-11 16:45 UTC, twinlensreflex submitted a review, later dismissed

2019-03-11 16:51 UTC, sareh submitted a review, later dismissed

2019-03-12 08:15 UTC, twinlensreflex submitted a review, later dismissed

2019-03-12 16:41 UTC, sareh approved these changes
👍 Works great locally.

2019-03-13 09:19 UTC, ChrisBAshton approved these changes
Looks good to me!

2019-03-13 16:47 UTC, ChrisBAshton commented
Does this PR solve #266?

2019-03-13 16:49 UTC, dr3 commented
@ChrisBAshton Nope

2019-03-14 12:26 UTC, dr3 commented
Tested locally. All acts as expected except for the amp stories which require a refresh, howeve that was the case before.

2019-03-14 12:26 UTC, merged