Alternative solution for RTL testing
BBC-archive/psammead pull request #336
Opened 2019-03-07 21:17 UTC by jblaut

Resolves #328

Alternative solution to https://github.com/bbc/psammead/pull/335.

**Overall change:**
We (the WS team) need to make sure that the current components will work with RTL left scripts. This is the beginning of such work.

**Code changes:**

- Installed and configured the [RTL Storybook Addon](https://www.npmjs.com/package/storybook-addon-rtl) to test components with RTL text

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-03-13 14:25 UTC, dr3 requested changes
LGTM :) Seeing as youve bumped the main psammead version (🎉 ) can you make a changelog please?

Also can we go to psammead v1.0.0 or 1.1.0? I think it will give us more freedom in our versioning

2019-03-13 15:21 UTC, jblaut commented
@dr3 I knew I was forgetting something! 😄 the CHANGELOG now exists, but I only added the new version and the changes I've made. Not sure if you guys wanna add more history to it...

2019-03-13 15:33 UTC, dr3 submitted a review, later dismissed
![](https://media.giphy.com/media/3oz8xRF0v9WMAUVLNK/giphy.gif)

2019-03-13 16:01 UTC, andrew-nowak submitted a review, later dismissed
LGTM

2019-03-13 16:15 UTC, pjlee11 commented on package.json
> +  "version": "1.1.0",
In the [Semver syntax](https://semver.org/) this should change to `1.0.0`. However, I spoke with @dr3 IRL and we've agreed that this should have already been `1.0.0` so it makes sense for this PR to bump to `1.1.0`. 

Adding this for future reference of npm versions.

2019-03-13 16:16 UTC, pjlee11 submitted a review, later dismissed
LGTM 👍

2019-03-18 15:22 UTC, sareh submitted a review, later dismissed
👍 Looks great.

2019-03-18 15:24 UTC, dr3 submitted a review, later dismissed

2019-03-18 15:37 UTC, jblaut commented
@dr3 @sareh freshly rebased, can I get some approvals? 😄

2019-03-18 15:38 UTC, dr3 approved these changes

2019-03-19 09:43 UTC, pjlee11 approved these changes

2019-03-20 13:16 UTC, merged