Add Stylelint and rc file
BBC-archive/psammead pull request #34
Opened 2018-11-22 14:49 UTC by dr3

Resolves #30

Adds style linting

- [ ] Tests added for new features
- [ ] Test engineer approval

2018-11-22 16:25 UTC, bcmn submitted a review, later dismissed

2018-11-22 16:53 UTC, bcmn submitted a review, later dismissed

2018-11-26 08:28 UTC, sareh requested changes
The stylelint work looks good. 
There's a change to the `test` script that needs to be made.

2018-11-26 08:28 UTC, sareh commented on package.json
> +    "test": "npm run test:lint && test:lint:css && npm run test:unit",
This needs to be `npm run test:lint:css`. Currently this doesn't run.

2018-11-26 08:51 UTC, sareh approved these changes
👍 Looks great!

2018-11-26 09:13 UTC, ChrisBAshton reviewed
Trying to make it error. If I edit styledExampleButton.js:

* add a `margin-top` after a `margin` declaration
  * throws a `Unexpected shorthand "margin" after "margin-top"` as expected
* add a `made-up-property: foo` line
  * throws a `Unexpected unknown property "made-up-property"` as expected
* add a `!important`
  * doesn't complain. I think it probably should.
* add an additional `color` property
  * doesn't complain!
* add an additional `color` property, _alongside_ a `made-up-property`
  * throws the `Unexpected unknown property` _and_ `Unexpected duplicate "color"` errors

So, think I've found a bug in the stylelint...! 🤔 

1. Worth raising the bug with the right Stylelint repo?
2. Worth implementing our own `!important` rule? (overrideable with a comment, of course)

Looks good so far 👍

2018-11-26 10:29 UTC, dr3 commented
@ChrisBAshton I think that should be a separate issue as this is for moving the rules from simorgh. Happy to make a new issue and move if you agree

2018-11-26 10:51 UTC, ChrisBAshton approved these changes
Didn't realise we had any style linting in Simorgh! Have now fixed [this stale issue](https://github.com/BBC-News/simorgh/issues/564).

Have raised #39 and #40. Happy to approve this PR as-is. Thanks!

2018-11-26 15:43 UTC, jamesbrumpton commented
LGTM

2018-11-26 15:44 UTC, merged