Constrain content width for SiteWideLinks
BBC-archive/psammead pull request #347
Opened 2019-03-11 15:55 UTC by sareh

Resolves #346

**Overall change:** Constrain content width for SiteWideLinks

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-03-11 16:03 UTC, dr3 requested changes
LGTM apart from this, great work

2019-03-11 16:03 UTC, dr3 commented on packages/components/psammead-sitewide-links/CHANGELOG.md
> +| 0.3.1   | [PR](https://github.com/BBC/psammead/pull/) Constrain content width to Group 5 min width. |
```suggestion
| 0.3.1   | [PR#347](https://github.com/BBC/psammead/pull/347) Constrain content width to Group 5 min width. |
```

2019-03-11 16:09 UTC, twinlensreflex submitted a review, later dismissed
All looks good to me too :)

2019-03-11 16:10 UTC, dr3 approved these changes
![](https://media.giphy.com/media/pa37AAGzKXoek/giphy.gif)

2019-03-11 16:10 UTC, twinlensreflex approved these changes
:+1:

2019-03-12 09:53 UTC, jamesbrumpton commented
👍

2019-03-12 09:55 UTC, merged