Add GEL Group A breakpoint
BBC-archive/psammead pull request #349
Opened 2019-03-12 10:16 UTC by DenisBBC

Resolves #348

**Overall change:** Added breakpoint for missing GEL Group A

**Code changes:**

- Added new `GEL_GROUP_A_MAX_WIDTH` constant
- Added new `FEATURE_PHONE_ONLY` breakpoint for 0 - 319 pixels
---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-03-12 11:13 UTC, dr3 approved these changes

2019-03-12 11:23 UTC, dr3 requested changes
Hey, Apologies, accidentally approved before, this needs change log, package bump etc :)

2019-03-12 11:37 UTC, sareh requested changes
Looks good! Just some package admin steps needed.

2019-03-12 11:37 UTC, sareh commented on packages/utilities/gel-foundations/src/breakpoints.js
>     These namings are based on the GEL description. They are also known as group B and group D
Could you please increase the version number in the `package.json` and `package-lock.json` & also add a line in the `CHANGELOG.md`?

2019-03-12 12:00 UTC, DenisBBC commented
Thank you for reminding about the versions. I have to get used to it :)

2019-03-12 12:03 UTC, dr3 commented on packages/utilities/gel-foundations/CHANGELOG.md
> +| ------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------ |
Looks like this file got caught by an auto-linter, can you reset the formatting please? 🙈

2019-03-12 15:03 UTC, sareh approved these changes
👍 Looks great!

2019-03-13 10:17 UTC, dr3 approved these changes
![](https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif)

2019-03-13 10:18 UTC, dr3 commented
@DenisBBC Is this PR not in a project? I cant see one attached

2019-03-13 10:27 UTC, DenisBBC commented
> @DenisBBC Is this PR not in a project? I cant see one attached
> 
> Also `I have assigned myself to this PR and the corresponding issues` has been ticked but you havent 🙈

It is, just assigned!

2019-03-13 10:57 UTC, merged