Add custom propTypes shape to Caption and Paragraph components
BBC-archive/psammead pull request #459
Opened 2019-04-23 10:01 UTC by DenisBBC

Resolves #425

**Overall change:** 
We should be more restrictive about what script 'object' we allow to pass to the component.
For this reason, we should add a custom propType shape matching the current scripts values.

**Code changes:**
- Replace `defaultProps` with `propTypes` in the `Caption` and `Paragraph` components
- Import script `propType` shape from `gel-foundations`

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-04-23 10:42 UTC, dr3 commented on packages/components/psammead-caption/src/index.jsx
Not sure why theres a blank space here
```suggestion
```

2019-04-23 10:43 UTC, dr3 commented on packages/components/psammead-caption/src/index.stories.jsx
> +        <Caption script={latin}>
Good spot :P

2019-04-23 10:44 UTC, dr3 reviewed
Just 1 blank line annoyance, LGTM if jenkins passes

2019-04-23 10:59 UTC, dr3 submitted a review, later dismissed

2019-04-23 11:14 UTC, sareh requested changes
The changes so far look great. I noticed that the `psammead-headings` component also needs this update: https://github.com/bbc/psammead/blob/9e5fdea65f923d4827311ec9dc7171adbe13d069/packages/components/psammead-headings/src/index.jsx#L46-L52

Could you please also add this to the PR?

2019-04-23 12:15 UTC, DenisBBC commented
> The changes so far look great. I noticed that the `psammead-headings` component also needs this update:
> 
> [psammead/packages/components/psammead-headings/src/index.jsx](https://github.com/bbc/psammead/blob/9e5fdea65f923d4827311ec9dc7171adbe13d069/packages/components/psammead-headings/src/index.jsx#L46-L52)
> 
> Lines 46 to 52 in [9e5fdea](/bbc/psammead/commit/9e5fdea65f923d4827311ec9dc7171adbe13d069)
> 
>  Headline.defaultProps = { 
>    script: objectOf(object).required, 
>  }; 
>   
>  SubHeading.defaultProps = { 
>    script: objectOf(object).required, 
>  }; 
> Could you please also add this to the PR?

@sareh There is already a PR in progress for the Headings component https://github.com/bbc/psammead/pull/428

2019-04-23 13:57 UTC, ghost submitted a review, later dismissed
👍

2019-04-23 14:51 UTC, ghost reviewed
Just a few changes to resolve possible merge conflict.

2019-04-23 14:51 UTC, sadickisaac commented on packages/components/psammead-caption/package.json
> +  "version": "1.0.2",
Update `package.json` . #446 has been merged 
```suggestion
  "version": "1.1.1",
```

2019-04-23 14:51 UTC, sadickisaac commented on packages/components/psammead-caption/package-lock.json
> +  "version": "1.0.2",
Update
```suggestion
  "version": "1.1.1",
```

2019-04-23 14:51 UTC, sadickisaac commented on packages/components/psammead-caption/CHANGELOG.md
> +| 1.0.2   | [PR#459](https://github.com/bbc/psammead/pull/459) Add custom propTypes shape |
Update `CHANGELOG.md`. #446 has been merged.

2019-04-24 08:08 UTC, ghost approved these changes
Looks great.

2019-04-24 08:51 UTC, dr3 approved these changes

2019-04-24 08:55 UTC, sareh approved these changes

2019-04-24 10:18 UTC, david-boydell commented
LGTM

2019-04-24 10:21 UTC, merged