Social embed fix no
BBC-archive/psammead pull request #4605
Opened 2021-12-03 14:56 UTC by jroebu14

Resolves #NUMBER

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)
- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2021-12-03 15:04 UTC, nicola-d-bbc approved these changes

2021-12-03 15:04 UTC, ryanmccombe approved these changes

2021-12-03 15:06 UTC, DarioR01 requested changes
There is a .yarn empty file on the file changes, I think it should be deleted

2021-12-03 15:25 UTC, DarioR01 approved these changes

2021-12-07 13:26 UTC, merged

2021-12-07 13:31 UTC, skwong25 commented
No manual testing required. Awaiting merge.