Add grid fallback to story promo
BBC-archive/psammead pull request #489
Opened 2019-05-01 13:27 UTC by DenisBBC

Resolves #471

**Overall change:**
Add a grid fallback to the story promo, that is supported for ie9,10&11.

**Code changes:**
- Use `max-widths` when `grid` is not supported
- Add `grid` styles within `@supports` CSS at-rule
---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-05-01 22:13 UTC, dr3 requested changes
Tested on IE11 & IE10, looks good.
Tested on IE9 & it doesnt seem to work.

Testing steps:
- In simorgh `npm i @bbc/psammead-story-promo`
- Change ArticleMain/index.js to [this code](https://gist.github.com/dr3/3c969d35b1e64b580cce004c9a15c08d)
- Run `npm link ../psammead/packages/components/psammead-story-promo`
- Run `npm run build` in psammead
- Run `npm run build && npm run start` in simorgh
- Open in browserstack on IE9
- See the issue
![image](https://user-images.githubusercontent.com/11341355/57045948-c17a6a00-6c66-11e9-826a-84021ef08d6c.png)

2019-05-03 12:56 UTC, david-boydell commented
Hi Dennis, I've found that when viewed as RTL the padding to separate the image and the text is not present.
![Uploading image.png…]()

2019-05-08 14:40 UTC, DenisBBC commented
> Tested on IE11 & IE10, looks good.
> Tested on IE9 & it doesnt seem to work.
> 
> Testing steps:
> 
> * In simorgh `npm i @bbc/psammead-story-promo`
> * Change ArticleMain/index.js to [this code](https://gist.github.com/dr3/3c969d35b1e64b580cce004c9a15c08d)
> * Run `npm link ../psammead/packages/components/psammead-story-promo`
> * Run `npm run build` in psammead
> * Run `npm run build && npm run start` in simorgh
> * Open in browserstack on IE9
> * See the issue
>   ![image](https://user-images.githubusercontent.com/11341355/57045948-c17a6a00-6c66-11e9-826a-84021ef08d6c.png)

Tested on IE9 and it works fine :)

<img width="956" alt="Screenshot 2019-05-08 at 15 39 39" src="https://user-images.githubusercontent.com/46446236/57383921-8cf73880-71a7-11e9-9960-4a087707bd7b.png">

2019-05-09 12:19 UTC, j-pendlebury submitted a review, later dismissed
looks good to me, just need to resolve some conflicts ⬇️

2019-05-09 13:19 UTC, dr3 requested changes
![image](https://user-images.githubusercontent.com/11341355/57456436-6f88a400-7265-11e9-891f-66b13997d52b.png)
At smaller breakpoints this doesnt seem to work for RTL

2019-05-09 13:19 UTC, dr3 commented on packages/components/psammead-story-promo/src/index.jsx
> +    padding-left: ${GEL_SPACING_DBL};
Ideally these would be consolidated into `padding: 0 ${GEL_SPACING_DBL}`

2019-05-09 13:57 UTC, dr3 approved these changes
Great work :D

2019-05-10 07:43 UTC, j-pendlebury approved these changes
![](https://media.giphy.com/media/rqzezYhA0Sdfq/giphy.gif)
LGTM 👍

2019-05-13 09:08 UTC, david-boydell commented
Looking good across all IE browsers

2019-05-13 09:14 UTC, merged