Caption paragraph padding
BBC-archive/psammead pull request #491
Opened 2019-05-02 09:44 UTC by eleanombre

Resolves #482
**Overall change:** _Remove padding-bottom from last child `Paragraph` elements in `Caption`._

**Code changes:**
- Added `Paragraph` to example caption in `Figure` Storybook
- Changed styling of `p` to `padding-bottom: 0;` when last child of `Caption`
- updated snapshots

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-05-02 14:22 UTC, sareh requested changes
👍  Looks great locally. I've added some package admin suggestions below.

2019-05-02 14:22 UTC, sareh commented on packages/components/psammead-caption/src/index.jsx
>    & i {
Could you please also update the Storybook story for `Caption` to have an example with multiple paragraphs? https://github.com/bbc/psammead/blob/47d91630e688bc6d854d0991ea74fa6a7c2ba523/packages/components/psammead-caption/src/index.stories.jsx#L43-L51

2019-05-02 14:22 UTC, sareh commented on packages/components/psammead-caption/src/index.jsx
>    @media (min-width: ${GEL_GROUP_4_SCREEN_WIDTH_MIN}) {
Please update the `package.json` version for `psammead-caption` (should be a patch increase). Likewise the `package-lock.json` and `CHANGELOG.md` files for this caption component.

2019-05-02 16:35 UTC, sareh commented on packages/components/psammead-caption/package.json
> +    "@bbc/psammead-paragraph": "^1.0.3",
This should be moved into `devDependencies`, since it's only used for the Storybook story, not in the source file.

2019-05-02 16:36 UTC, sareh commented on packages/components/psammead-figure/CHANGELOG.md
> +| 0.1.14  | [PR#491](https://github.com/bbc/psammead/pull/491) Updates test to account for new styling on paragraph elements in captions |
```suggestion
| 0.1.14  | [PR#491](https://github.com/bbc/psammead/pull/491) Updates Storybook to account for new styling on paragraph elements in captions |
```

2019-05-02 17:09 UTC, dr3 commented on packages/components/psammead-caption/src/index.jsx
>      padding: ${GEL_SPACING} 0;
As figure [has 24 padding already](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-figure/src/index.jsx#L6), I think caption needs to have zero bottom padding at all breakpoints

2019-05-07 11:32 UTC, sareh commented on packages/components/psammead-caption/src/index.jsx
>      padding: ${GEL_SPACING} ${GEL_MARGIN_ABOVE_400PX};
```suggestion
    padding: ${GEL_SPACING} ${GEL_MARGIN_ABOVE_400PX} 0;
```
You're missing the padding-bottom 0 for this breakpoint.

2019-05-07 13:28 UTC, sareh submitted a review, later dismissed
👍 Looks good locally!

2019-05-07 15:07 UTC, Bopchy submitted a review, later dismissed
Looks good 👍

2019-05-09 12:16 UTC, sareh approved these changes

2019-05-09 12:29 UTC, Bopchy approved these changes

2019-05-09 12:33 UTC, jamesbrumpton commented
MERGIO

2019-05-09 12:34 UTC, merged