Pass an optional prop of 'id' to SubHeading
BBC-archive/psammead pull request #504
Opened 2019-05-08 10:24 UTC by rhell

Resolves #88 

**Overall change:** 
This removes the required `text` prop, and adds an optional `id` prop to the `SubHeading` in the `psammead-headings` package. This is to allow subheadings to have anchors, should they be required.

**Code changes:**

- Removed `text` prop
- Added optional `id` prop
- Updated storybook
- Updated tests

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-05-08 12:24 UTC, sareh requested changes
@rhell Great work so far. I've added some comments below.

2019-05-08 12:24 UTC, sareh commented on packages/components/psammead-headings/package.json
>    "name": "@bbc/psammead-headings",
The `psammead-headings/package-lock.json` should also have the version number change. You can generate package-lock changes when running `npm run install:packages` at the top level, or an `npm install` within the directory.

2019-05-08 12:24 UTC, sareh commented on packages/components/psammead-headings/src/index.jsx
> +  id: string,
`id` is a supported DOM Attribute in React, so it does not need to be defined as a prop. https://reactjs.org/docs/dom-elements.html

2019-05-08 12:24 UTC, sareh commented on packages/components/psammead-headings/src/index.stories.jsx
> +        <SubHeading id={id} script={latin}>
It's great to adding this Storybook story here, with the input provider. 👍

2019-05-08 12:24 UTC, sareh commented on packages/components/psammead-headings/CHANGELOG.md
> +| 2.0.0   | [PR#504](https://github.com/bbc/psammead/pull/504) Remove required text prop |
👍 Thanks for remembering the Changelog.

2019-05-08 12:47 UTC, 12 commented on packages/components/psammead-headings/package.json
>    "name": "@bbc/psammead-headings",
Ah yeah, thanks for that!

2019-05-08 14:31 UTC, Bopchy submitted a review, later dismissed
Looks good 👍

2019-05-08 15:42 UTC, sareh submitted a review, later dismissed
👍 Looks good!

2019-05-08 15:46 UTC, sareh commented on packages/components/psammead-headings/CHANGELOG.md
>  |---------|-------------|
Just remembered that the Readme needs updating too, to remove reference to the `id` attribute being generated. https://github.com/bbc/psammead/blob/cabd0c0aff674831f916e1bc1da5988efe03739a/packages/components/psammead-headings/README.md#when-to-use-this-component

2019-05-08 15:51 UTC, jamesbrumpton commented
LGTM. Happy for this to be merged.

2019-05-08 16:23 UTC, sareh submitted a review, later dismissed
🎉

2019-05-09 06:46 UTC, Bopchy submitted a review, later dismissed

2019-05-09 09:55 UTC, pjlee11 commented on packages/components/psammead-headings/README.md
> +<SubHeading id="some-subheadline">Some subheadline</SubHeading>
```suggestion
<SubHeading id="some-subheadline" script={latin}>Some subheadline</SubHeading>
```

2019-05-09 10:00 UTC, pjlee11 submitted a review, later dismissed
Nice one - debut PR! 🎉 

![](https://media.giphy.com/media/2zcQjd74pAkfbRUcsq/giphy.gif)

2019-05-09 11:59 UTC, pjlee11 approved these changes

2019-05-09 12:27 UTC, sareh approved these changes

2019-05-09 13:14 UTC, merged