Update GEL Typography values
BBC-archive/psammead pull request #586
Opened 2019-06-05 10:44 UTC by DenisBBC

Resolves #565

**Overall change:** 
Update the Typography values to match with the latest changes in the UX Font Stacks & Styles spreadsheet. 

**Code changes:**
- Go through all the scripts files and update the values that have changed.
- Update `getTypeSizes` test

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-06-05 11:51 UTC, dr3 requested changes
Can this be a breaking change? Dont want to pull it in by mistake,

Other than that LGTM so long as the UX review is very intensive to ensure the values are correct

2019-06-12 06:59 UTC, ghost submitted a review, later dismissed

2019-06-12 08:53 UTC, dr3 commented on packages/utilities/gel-foundations/CHANGELOG.md
> +| ------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------ |
Could you add the prettier ignore comment here and reset the styling please?

2019-06-12 12:36 UTC, ghost approved these changes

2019-06-12 12:38 UTC, dr3 approved these changes

2019-06-12 13:00 UTC, WeimingFan commented
This Typography values is approved against UX GEL setting.  Fan

2019-06-12 13:01 UTC, WeimingFan commented
This Typography values is approved against UX GEL setting.  Fan

2019-06-12 14:02 UTC, jamesbrumpton commented
LGTM.

2019-06-12 14:16 UTC, merged