Storybook version => 5.1.3
BBC-archive/psammead pull request #594
Opened 2019-06-07 13:14 UTC by jblaut

Resolves N/A

**Overall change:**
Use version 5.1.3 of Storybook. This is version contains a fix for a bug when viewing components in a new tab canvas. More info here: https://github.com/storybookjs/storybook/issues/6800

---

- [x] I have assigned myself to this PR and the corresponding issues
- ~~Tests added for new features~~
- [ ] Test engineer approval

2019-06-07 13:17 UTC, DenisHdz requested changes
CHANGELOG needs to be updated :)

2019-06-07 13:19 UTC, jblaut commented
@DenisBBC I didn't bump the version of Psammead, which means no need for CHANGELOG update. Unless I need to bump version of Psammead as well? 🤔

2019-06-07 13:40 UTC, jblaut commented
@DenisBBC done now 😄

2019-06-07 13:50 UTC, DenisHdz submitted a review, later dismissed

2019-06-07 14:38 UTC, dr3 submitted a review, later dismissed

2019-06-10 12:13 UTC, jamesbhobbs requested changes
There are a bunch of other storybook updates available, e.g. https://github.com/bbc/psammead/pull/603 Suggest they are all done at once.

2019-06-11 09:38 UTC, dr3 requested changes

2019-06-11 09:38 UTC, dr3 commented on CHANGELOG.md
> +| 1.1.8   | [PR#594](https://github.com/BBC/psammead/pull/594) Bump Storybook version |
```suggestion
| 1.1.8   | [PR#594](https://github.com/BBC/psammead/pull/594) Bump various dependencies inc storybook and lerna |
```

2019-06-11 10:10 UTC, DenisHdz approved these changes
![](https://media.giphy.com/media/AEzIKaaOTkO9eyGUDK/giphy.gif)

2019-06-11 11:55 UTC, andrew-nowak approved these changes
This introduces a warning in the console in storybook:
`The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".`
But this is due to a known issue in storybook: https://github.com/storybookjs/storybook/issues/6998 and I don't think blocks this going forward :)

Otherwise lgtm but needs code owner approval

2019-06-11 11:55 UTC, aacn500 commented on packages/utilities/psammead-assets/src/svgs.test.jsx
> +          viewBox={`${svgs[svgName].viewbox.width} ${svgs[svgName].viewbox.height}`}
🤩

2019-06-11 12:25 UTC, dr3 approved these changes

2019-06-12 10:21 UTC, jamesbhobbs approved these changes

2019-06-13 13:27 UTC, jblaut commented
After updating versions of all the dependencies in this PR, the inputProvider doesn't update values for different stories, e.g.
![image](https://user-images.githubusercontent.com/13763899/59436253-2b01a280-8de7-11e9-9708-ce3e82427e8e.png)
The SVG width doesn't update from the news one, which makes the SVG look tiny

![image](https://user-images.githubusercontent.com/13763899/59436329-4e2c5200-8de7-11e9-8a77-c32afa38c86f.png)
Headline text doesn't update to Afrique, stays English instead.

Will raise a new PR to update to version 5.1.4 of Storybook, which includes some `core-js` bug fixes.

2019-06-13 13:27 UTC, closed without merging