Fix changelog title for story promo
BBC-archive/psammead pull request #628
Opened 2019-06-13 15:44 UTC by rhell

Resolves #NUMBER

**Overall change:** Fix changelog title for `psammead-story-promo`

**Code changes:**

- Update to CHANGELOG.md

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-06-13 16:21 UTC, pjlee11 approved these changes

2019-06-13 16:22 UTC, pjlee11 requested changes
Ignore the approval above, prettier hasn't been ignored on the changelog hence all the extra whitespace

2019-06-14 08:24 UTC, ghost approved these changes

2019-06-14 08:32 UTC, dr3 approved these changes
<img src="https://media.giphy.com/media/5yLgocgRS7h1RgXsili/giphy.gif" width="100%" />

2019-06-14 08:34 UTC, pjlee11 approved these changes

2019-06-14 10:18 UTC, staylos92 commented
This doesn't need testing by a tester

2019-06-14 11:23 UTC, merged