Change port number
BBC-archive/psammead pull request #630
Opened 2019-06-14 09:48 UTC by ryanmccombe

Resolves #NUMBER

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-06-14 09:51 UTC, pjlee11 commented
Could you change the title to explicitly state this changes storybook's port number please 😄

2019-06-19 14:52 UTC, 12 approved these changes

2019-06-19 17:11 UTC, dr3 requested changes

2019-06-19 17:11 UTC, dr3 commented on CHANGELOG.md
> +| 1.1.10  | [PR#630](https://github.com/BBC/psammead/pull/630) Change storybook port to 8180 |
Need to bump the package and package-lock to `1.1.10`

2019-06-20 18:41 UTC, dr3 approved these changes

2019-06-20 19:51 UTC, benjaminhobbs commented
This doesn't need test.

2019-06-21 09:10 UTC, merged