Update brand component story on Storybook
BBC-archive/psammead pull request #642
Opened 2019-06-17 12:55 UTC by Bopchy

Resolves #606 

**Overall change:** _Update brand component story on Storybook to include knobs for `product` and `serviceLocalisedName`._

**Code changes:**

- _Add knobs for `product` and `serviceLocalisedName` to the brand component story on Storybook.._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-06-17 15:46 UTC, ghost requested changes

2019-06-17 15:46 UTC, sadickisaac commented on packages/components/psammead-brand/CHANGELOG.md
> +| 4.1.0   | [PR#642](https://github.com/bbc/psammead/pull/642) Add product and serviceLocalisedName knobs on storybook |
```suggestion
| 4.0.1   | [PR#642](https://github.com/bbc/psammead/pull/642) Add product and serviceLocalisedName knobs on storybook |
```

2019-06-17 15:46 UTC, ghost commented on packages/components/psammead-brand/package.json
> +  "version": "4.1.0",
```suggestion
  "version": "4.0.1",
```

2019-06-17 15:46 UTC, ghost commented on packages/components/psammead-brand/src/index.stories.jsx
> +  const productInput = text('Product', 'Default Brand Name');
Could we have the default value be `BBC News` as that is the current product we have. And also `serviceLocalisedName` to one of the services. i.e `Igbo` since **News** isn't a service localised name for any service.

2019-06-18 08:06 UTC, ghost approved these changes
LGTM 👍

2019-06-18 08:08 UTC, j-pendlebury approved these changes
Looks good 👍

2019-06-18 10:29 UTC, david-boydell commented
Looks good, ready for merge.

2019-06-18 11:35 UTC, merged