Brand should have max width of 80rem
BBC-archive/psammead pull request #649
Opened 2019-06-18 15:23 UTC by Bopchy

Resolves #645 

**Overall change:** _Update brand to have a max-width of 80rem._

**Code changes:**

- _Update brand to have max-width of 80rem._
- _Update snapshots._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-06-18 18:41 UTC, dr3 commented on packages/components/psammead-brand/src/index.jsx
> +  max-width: ${GEL_GROUP_4_SCREEN_WIDTH_MAX};
Even though [they are the same value](https://github.com/bbc/psammead/blob/7cfe6c0535ed6f95e98ee4fd7eeefc55b212e714/packages/utilities/gel-foundations/src/breakpoints.js#L29-L31) 🙈 Can you use `GEL_GROUP_5_SCREEN_WIDTH_MIN` here instead please :P Its what we used before :)

2019-06-18 18:44 UTC, dr3 commented on packages/components/psammead-brand/src/index.jsx
>    <Fragment>
Also, this doesnt work when the svg is a link weirdly :P May need to move the wrapper up a bit

2019-06-19 09:00 UTC, j-pendlebury requested changes
needs a package-lock update, but otherwise LGTM 👍

2019-06-19 09:12 UTC, j-pendlebury approved these changes

2019-06-19 09:13 UTC, dr3 approved these changes

2019-06-19 12:54 UTC, david-boydell commented
Looks good, this is ready for merge!

2019-06-19 13:08 UTC, merged